{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "0.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.2-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-0.0.2-SNAPSHOT.jar",
          "size": 338880,
          "sha512": "402ae9aec2fe9ec434074ee0e435e701eccfa5d54d7c28baa56f11aa10faeb2ed664e6df75af052fc5e21b31f640fcee0696f22c1ee37c3125d6211165bd9525",
          "sha256": "a7e1bdc76eef007e125b14f771fe6fcd28f6ded491c91419398c78d1b8023255",
          "sha1": "d6c08c133a82dfa8be16246571554927bc4caf9f",
          "md5": "65efb02e78491d0d4a444e9997c8f08d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.2-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-0.0.2-SNAPSHOT.jar",
          "size": 338880,
          "sha512": "402ae9aec2fe9ec434074ee0e435e701eccfa5d54d7c28baa56f11aa10faeb2ed664e6df75af052fc5e21b31f640fcee0696f22c1ee37c3125d6211165bd9525",
          "sha256": "a7e1bdc76eef007e125b14f771fe6fcd28f6ded491c91419398c78d1b8023255",
          "sha1": "d6c08c133a82dfa8be16246571554927bc4caf9f",
          "md5": "65efb02e78491d0d4a444e9997c8f08d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.2-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.2-SNAPSHOT-sources.jar",
          "size": 38821,
          "sha512": "8fb8e95613a12023dfaac78d528cfdced58a5776a7d185fbf08e19e8a88aaae75f4e97b8dfcc4e19ca2b248ac7aca636ddb2094c472de2501509c811e8bed973",
          "sha256": "e2ec567b49178a6ec9c8c94f0c2536d4ce1e05d97e29bad2f864522b2975d802",
          "sha1": "673ca5dae5c8e2bc5b175eb15d19c1538c8ca099",
          "md5": "8aa428ffc932eb86b8a3cf8d3f0e4d43"
        },
        {
          "name": "dokkatoo-plugin-0.0.2-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.2-SNAPSHOT-sources.jar",
          "size": 38821,
          "sha512": "8fb8e95613a12023dfaac78d528cfdced58a5776a7d185fbf08e19e8a88aaae75f4e97b8dfcc4e19ca2b248ac7aca636ddb2094c472de2501509c811e8bed973",
          "sha256": "e2ec567b49178a6ec9c8c94f0c2536d4ce1e05d97e29bad2f864522b2975d802",
          "sha1": "673ca5dae5c8e2bc5b175eb15d19c1538c8ca099",
          "md5": "8aa428ffc932eb86b8a3cf8d3f0e4d43"
        },
        {
          "name": "dokkatoo-plugin-0.0.2-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.2-SNAPSHOT-sources.jar",
          "size": 38821,
          "sha512": "8fb8e95613a12023dfaac78d528cfdced58a5776a7d185fbf08e19e8a88aaae75f4e97b8dfcc4e19ca2b248ac7aca636ddb2094c472de2501509c811e8bed973",
          "sha256": "e2ec567b49178a6ec9c8c94f0c2536d4ce1e05d97e29bad2f864522b2975d802",
          "sha1": "673ca5dae5c8e2bc5b175eb15d19c1538c8ca099",
          "md5": "8aa428ffc932eb86b8a3cf8d3f0e4d43"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.2-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-0.0.2-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
