{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "0.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.2-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-0.0.2-SNAPSHOT.jar",
          "size": 337449,
          "sha512": "a1ae5bad53db320c7a724442368b65252705e51f435bf3c4796f82d75af757523bba460281e15b7a44d2d599911963edc436813d8b37521eb719da458ea13c9a",
          "sha256": "9b488652b85a09e9ac1f3f2b39755f980a160289c498e41da14e247aa7dff14e",
          "sha1": "f66b9a5bc3713b9b91e07547eb2c17e9561fe70f",
          "md5": "03199ee9b56cbda697836952f1bc2b25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.2-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-0.0.2-SNAPSHOT.jar",
          "size": 337449,
          "sha512": "a1ae5bad53db320c7a724442368b65252705e51f435bf3c4796f82d75af757523bba460281e15b7a44d2d599911963edc436813d8b37521eb719da458ea13c9a",
          "sha256": "9b488652b85a09e9ac1f3f2b39755f980a160289c498e41da14e247aa7dff14e",
          "sha1": "f66b9a5bc3713b9b91e07547eb2c17e9561fe70f",
          "md5": "03199ee9b56cbda697836952f1bc2b25"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.2-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.2-SNAPSHOT-sources.jar",
          "size": 38798,
          "sha512": "5dfcfc98d083c43bfb72bbb1bc224907ed23a53a7dc1be9de6ba1fcd1708967a721705e021b7ac0db1d1d830cb305275bc4c7d12d5dfafd08ef760916ef23e2d",
          "sha256": "5b54a28cc7345447c7d2befb15f02efa255386188e9dc1ccf673e4f52cdb3734",
          "sha1": "a9d44dd67ebacfd7dc1a697e7c104262c489b8d7",
          "md5": "2e60a2766579212baf788a903e917482"
        },
        {
          "name": "dokkatoo-plugin-0.0.2-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.2-SNAPSHOT-sources.jar",
          "size": 38798,
          "sha512": "5dfcfc98d083c43bfb72bbb1bc224907ed23a53a7dc1be9de6ba1fcd1708967a721705e021b7ac0db1d1d830cb305275bc4c7d12d5dfafd08ef760916ef23e2d",
          "sha256": "5b54a28cc7345447c7d2befb15f02efa255386188e9dc1ccf673e4f52cdb3734",
          "sha1": "a9d44dd67ebacfd7dc1a697e7c104262c489b8d7",
          "md5": "2e60a2766579212baf788a903e917482"
        },
        {
          "name": "dokkatoo-plugin-0.0.2-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.2-SNAPSHOT-sources.jar",
          "size": 38798,
          "sha512": "5dfcfc98d083c43bfb72bbb1bc224907ed23a53a7dc1be9de6ba1fcd1708967a721705e021b7ac0db1d1d830cb305275bc4c7d12d5dfafd08ef760916ef23e2d",
          "sha256": "5b54a28cc7345447c7d2befb15f02efa255386188e9dc1ccf673e4f52cdb3734",
          "sha1": "a9d44dd67ebacfd7dc1a697e7c104262c489b8d7",
          "md5": "2e60a2766579212baf788a903e917482"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.2-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-0.0.2-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
