{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "0.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.2-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-0.0.2-SNAPSHOT.jar",
          "size": 336072,
          "sha512": "8eb9a091462baa9dcfbf6d82924d1d42c43a7a830120d65b8896f2ed706fa81b916b17ee3a035acd810692222b888c302f7f1c40fbcd5e69c8d4927495d27cfb",
          "sha256": "1b8d09cac95ddaf65d3ede8a9b8f7fb5b9df745a88059dd02613ffe408e4081e",
          "sha1": "b305f19059f6bbff14d8004fea5892946fe72a24",
          "md5": "7244dd9ab313f6c010152022960f4622"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.2-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-0.0.2-SNAPSHOT.jar",
          "size": 336072,
          "sha512": "8eb9a091462baa9dcfbf6d82924d1d42c43a7a830120d65b8896f2ed706fa81b916b17ee3a035acd810692222b888c302f7f1c40fbcd5e69c8d4927495d27cfb",
          "sha256": "1b8d09cac95ddaf65d3ede8a9b8f7fb5b9df745a88059dd02613ffe408e4081e",
          "sha1": "b305f19059f6bbff14d8004fea5892946fe72a24",
          "md5": "7244dd9ab313f6c010152022960f4622"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.2-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.2-SNAPSHOT-sources.jar",
          "size": 38426,
          "sha512": "262c352ebb6e73d2d0039b0ec272f713c12fd19eaf26006b2d93080ad04ba92b0877c09d8a9c62fb3880c85f7c50baedbeeca2a2286d33ac68e5e6c8ae556eba",
          "sha256": "4e3f3c312689b6f68cd9368afaa09e9b0dc43b52a0526cc4a665fe4756381673",
          "sha1": "d168ff3514e0b94669c46ae31e5ee6687abb8cbd",
          "md5": "bfc25e96ce2d49af4163a56ffe381dee"
        },
        {
          "name": "dokkatoo-plugin-0.0.2-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.2-SNAPSHOT-sources.jar",
          "size": 38426,
          "sha512": "262c352ebb6e73d2d0039b0ec272f713c12fd19eaf26006b2d93080ad04ba92b0877c09d8a9c62fb3880c85f7c50baedbeeca2a2286d33ac68e5e6c8ae556eba",
          "sha256": "4e3f3c312689b6f68cd9368afaa09e9b0dc43b52a0526cc4a665fe4756381673",
          "sha1": "d168ff3514e0b94669c46ae31e5ee6687abb8cbd",
          "md5": "bfc25e96ce2d49af4163a56ffe381dee"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.2-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-0.0.2-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
