{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "0.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.3-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-0.0.3-SNAPSHOT.jar",
          "size": 318118,
          "sha512": "9d84db875524a19f47b9da12ca639be1400b29cf7e0e60d1c1ab7b4c87dd122b00fc38b20e3dddc016074c6ee8e5de78cff38aa9c73edac43c275fd576b6c7b6",
          "sha256": "e66b607f15c1ef41e08396ed15ed27ccf1d38093e9dfce06d0f1cacbef9e8322",
          "sha1": "b460c70844eb16636300793d34ca7d56c5242e40",
          "md5": "c198a0c91c4105bdb4ab4a1d4186fc58"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.3-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-0.0.3-SNAPSHOT.jar",
          "size": 318118,
          "sha512": "9d84db875524a19f47b9da12ca639be1400b29cf7e0e60d1c1ab7b4c87dd122b00fc38b20e3dddc016074c6ee8e5de78cff38aa9c73edac43c275fd576b6c7b6",
          "sha256": "e66b607f15c1ef41e08396ed15ed27ccf1d38093e9dfce06d0f1cacbef9e8322",
          "sha1": "b460c70844eb16636300793d34ca7d56c5242e40",
          "md5": "c198a0c91c4105bdb4ab4a1d4186fc58"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.3-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.3-SNAPSHOT-sources.jar",
          "size": 38354,
          "sha512": "ec43000da23211f8a10e245bd162dc9ceb422855c28d50d06ef28fd6cd1eafcfb20fb8f8cae35bd4d49a9697aca9fb3936c9673220c0768a4aa55a2ac6c706d5",
          "sha256": "215b81e1f353ad0497036db6079dd09ed8565fdb1efd48398b7fe486d04b01eb",
          "sha1": "e82522d2482bd61a174cd6bf5e3b8ab140845384",
          "md5": "50b89f9f34583414ffb5d83edceb4b5f"
        },
        {
          "name": "dokkatoo-plugin-0.0.3-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.3-SNAPSHOT-sources.jar",
          "size": 38354,
          "sha512": "ec43000da23211f8a10e245bd162dc9ceb422855c28d50d06ef28fd6cd1eafcfb20fb8f8cae35bd4d49a9697aca9fb3936c9673220c0768a4aa55a2ac6c706d5",
          "sha256": "215b81e1f353ad0497036db6079dd09ed8565fdb1efd48398b7fe486d04b01eb",
          "sha1": "e82522d2482bd61a174cd6bf5e3b8ab140845384",
          "md5": "50b89f9f34583414ffb5d83edceb4b5f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.3-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-0.0.3-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
