{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "0.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.3-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-0.0.3-SNAPSHOT.jar",
          "size": 323546,
          "sha512": "6dfa4cd0719831bd54a7d8b32f4d53f08142d5fe6138134af380954a4e9c9df0e55ab473a0b4674494fde3edbcfb9dc343f1e89496f32e31ebb3689e40a87690",
          "sha256": "1f96960738c154bb87d307772f5f6acb0d9e50b7e94c2ca3bd4788d748c5e601",
          "sha1": "f4a4f1a6ef6690c49b1de344c84cabd5198dc9cf",
          "md5": "b770bc4d60b2d57187cdc44b63682bff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.3-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-0.0.3-SNAPSHOT.jar",
          "size": 323546,
          "sha512": "6dfa4cd0719831bd54a7d8b32f4d53f08142d5fe6138134af380954a4e9c9df0e55ab473a0b4674494fde3edbcfb9dc343f1e89496f32e31ebb3689e40a87690",
          "sha256": "1f96960738c154bb87d307772f5f6acb0d9e50b7e94c2ca3bd4788d748c5e601",
          "sha1": "f4a4f1a6ef6690c49b1de344c84cabd5198dc9cf",
          "md5": "b770bc4d60b2d57187cdc44b63682bff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.3-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.3-SNAPSHOT-sources.jar",
          "size": 39175,
          "sha512": "a2a01c46325d202823078248a9db5a918f57a550dfbfa52c6665b0ae856ab31da7abe97617901b5ec7bdb096077129acae2b38e221900aa83fd905b4a09eca45",
          "sha256": "deb226dbc568c732d037d916fb3bd730b45f1bab8dc4ae62eafe86941106f243",
          "sha1": "6a79fe62e15741ecae5656fd4bb71da0a90fb5b1",
          "md5": "c88c47a5939862644127c3cc332102e8"
        },
        {
          "name": "dokkatoo-plugin-0.0.3-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.3-SNAPSHOT-sources.jar",
          "size": 39175,
          "sha512": "a2a01c46325d202823078248a9db5a918f57a550dfbfa52c6665b0ae856ab31da7abe97617901b5ec7bdb096077129acae2b38e221900aa83fd905b4a09eca45",
          "sha256": "deb226dbc568c732d037d916fb3bd730b45f1bab8dc4ae62eafe86941106f243",
          "sha1": "6a79fe62e15741ecae5656fd4bb71da0a90fb5b1",
          "md5": "c88c47a5939862644127c3cc332102e8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.3-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-0.0.3-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
