{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.1-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.1.1-SNAPSHOT.jar",
          "size": 391073,
          "sha512": "de4476ee9179393ae3c5dff072778b6598fd6e4d337550939697f7b35c15f027658c0c06c6cac0ac39d21b0d3b58e7616ec1eaa65b35c7e10e5721516f9fcd89",
          "sha256": "baed88b4547f0dc9ea882d24aeb04ec38f4c9a1fa28afe1facc4340261528e8a",
          "sha1": "fe8e069d6b974ff1a06d4fe99b46285be4544fbc",
          "md5": "592bf160f10f77de0bcf61d0165ea837"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.1-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.1.1-SNAPSHOT.jar",
          "size": 391073,
          "sha512": "de4476ee9179393ae3c5dff072778b6598fd6e4d337550939697f7b35c15f027658c0c06c6cac0ac39d21b0d3b58e7616ec1eaa65b35c7e10e5721516f9fcd89",
          "sha256": "baed88b4547f0dc9ea882d24aeb04ec38f4c9a1fa28afe1facc4340261528e8a",
          "sha1": "fe8e069d6b974ff1a06d4fe99b46285be4544fbc",
          "md5": "592bf160f10f77de0bcf61d0165ea837"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.1.1-SNAPSHOT-sources.jar",
          "size": 49503,
          "sha512": "a0768562d9256439cadb1bbbca59ec967dc58fbee5b317fe2b180a33ec24597f59e2dfd1e66781e6984a17838926311485058f37227efc22a0deef9caa7769e1",
          "sha256": "fd3a84635fb302c61c90c6ecf7954b64db8f9ca522efe4e129009a75ee65988c",
          "sha1": "4f1ce9964f62c7d1f0bf91d2aebf7ea14ff67948",
          "md5": "3161d880935acebf068eba0fc8ca37f6"
        },
        {
          "name": "dokkatoo-plugin-1.1.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.1.1-SNAPSHOT-sources.jar",
          "size": 49503,
          "sha512": "a0768562d9256439cadb1bbbca59ec967dc58fbee5b317fe2b180a33ec24597f59e2dfd1e66781e6984a17838926311485058f37227efc22a0deef9caa7769e1",
          "sha256": "fd3a84635fb302c61c90c6ecf7954b64db8f9ca522efe4e129009a75ee65988c",
          "sha1": "4f1ce9964f62c7d1f0bf91d2aebf7ea14ff67948",
          "md5": "3161d880935acebf068eba0fc8ca37f6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.1-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-1.1.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
