{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.1-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.1.1-SNAPSHOT.jar",
          "size": 385766,
          "sha512": "febb980bc31432efd9f1e659bd9d556dd3e3a8bd683187921fedf2bdd1a6020b7f720d73b046266cd0df690cf939af87b1e6815b3292cf9c658b52c49240a7d3",
          "sha256": "e5203abecfcaf9bbc936abba49f5eecd0d5f327f9d140383627ba64a4e7c0956",
          "sha1": "7a1aca9982e687ccac76c5e632f4dc87ff89010b",
          "md5": "71b9e3093b47a45d193dddb0c9a1b7fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.1-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.1.1-SNAPSHOT.jar",
          "size": 385766,
          "sha512": "febb980bc31432efd9f1e659bd9d556dd3e3a8bd683187921fedf2bdd1a6020b7f720d73b046266cd0df690cf939af87b1e6815b3292cf9c658b52c49240a7d3",
          "sha256": "e5203abecfcaf9bbc936abba49f5eecd0d5f327f9d140383627ba64a4e7c0956",
          "sha1": "7a1aca9982e687ccac76c5e632f4dc87ff89010b",
          "md5": "71b9e3093b47a45d193dddb0c9a1b7fd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.1.1-SNAPSHOT-sources.jar",
          "size": 49020,
          "sha512": "e4f1e865c34e1f4947034a914844c0290a49eed506292a879e1f862c7e872fb230542cd6b0fd9a0b9d419cec58dcfff48fac00841c9d133235346898d8e5ddc5",
          "sha256": "6521f7271888f795df632837f79cc7836694c12e3101791c6b5de778ab372886",
          "sha1": "d72fe0bc7e6145ebcf3691ae621c83826b46f9f4",
          "md5": "7d580105ff71dddbbd64d21f5e46fd64"
        },
        {
          "name": "dokkatoo-plugin-1.1.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.1.1-SNAPSHOT-sources.jar",
          "size": 49020,
          "sha512": "e4f1e865c34e1f4947034a914844c0290a49eed506292a879e1f862c7e872fb230542cd6b0fd9a0b9d419cec58dcfff48fac00841c9d133235346898d8e5ddc5",
          "sha256": "6521f7271888f795df632837f79cc7836694c12e3101791c6b5de778ab372886",
          "sha1": "d72fe0bc7e6145ebcf3691ae621c83826b46f9f4",
          "md5": "7d580105ff71dddbbd64d21f5e46fd64"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.1-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-1.1.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
