{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.1-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.1.1-SNAPSHOT.jar",
          "size": 388567,
          "sha512": "baa2e649184977c31cab57b28177e0a53661a9dcd56deafa411326f9ad4ce7cc6b2dd49ae7f965f581f445ecbcdd83c68d05660a838418a24bf3c0eb34479247",
          "sha256": "9ba9a82d64af814381b000256b1f273331ae8bf13bde9bac0772957d9929a18b",
          "sha1": "5e13d172d13ead490a715f65020faa00b7a5670e",
          "md5": "291ebb6158282a9408e3d066f13e3baa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.1-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.1.1-SNAPSHOT.jar",
          "size": 388567,
          "sha512": "baa2e649184977c31cab57b28177e0a53661a9dcd56deafa411326f9ad4ce7cc6b2dd49ae7f965f581f445ecbcdd83c68d05660a838418a24bf3c0eb34479247",
          "sha256": "9ba9a82d64af814381b000256b1f273331ae8bf13bde9bac0772957d9929a18b",
          "sha1": "5e13d172d13ead490a715f65020faa00b7a5670e",
          "md5": "291ebb6158282a9408e3d066f13e3baa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.1.1-SNAPSHOT-sources.jar",
          "size": 49180,
          "sha512": "e6bb73fbaf2303cbbdfc16b014e9e3e554d02b39c3bc2e280914d00a484116020e16b73574a2fd43a440ad48f05981f74f9968f9cf2e92ab438274c55a30661c",
          "sha256": "489f34e8d70d165f7e229c592defbfceb1b5bf9fc44c353d5a44e5d3e729ca8f",
          "sha1": "c2585329d6f653014a90a25369c422baec4c52a6",
          "md5": "25fc560db5eef216bfb5a631c8f898ba"
        },
        {
          "name": "dokkatoo-plugin-1.1.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.1.1-SNAPSHOT-sources.jar",
          "size": 49180,
          "sha512": "e6bb73fbaf2303cbbdfc16b014e9e3e554d02b39c3bc2e280914d00a484116020e16b73574a2fd43a440ad48f05981f74f9968f9cf2e92ab438274c55a30661c",
          "sha256": "489f34e8d70d165f7e229c592defbfceb1b5bf9fc44c353d5a44e5d3e729ca8f",
          "sha1": "c2585329d6f653014a90a25369c422baec4c52a6",
          "md5": "25fc560db5eef216bfb5a631c8f898ba"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.1-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-1.1.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
