{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.1-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.1.1-SNAPSHOT.jar",
          "size": 388012,
          "sha512": "373b00308b8096de502dfc4b03961409753a2601e068e9c3726ba00e1298dcc1bb79e2e83f27f034043fa0ceb252f96bd4eab130a49011d9ddb813c1a0b1af75",
          "sha256": "7339f8a6a0fed270bfbe45538cffae273f2ada5601c9bc5f179397a45de41bc3",
          "sha1": "68b6603dcfb5689545bc934bb5e99c5d638b8b57",
          "md5": "f7ef824dac6fdfca4aa3c5e82411e3c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.1-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.1.1-SNAPSHOT.jar",
          "size": 388012,
          "sha512": "373b00308b8096de502dfc4b03961409753a2601e068e9c3726ba00e1298dcc1bb79e2e83f27f034043fa0ceb252f96bd4eab130a49011d9ddb813c1a0b1af75",
          "sha256": "7339f8a6a0fed270bfbe45538cffae273f2ada5601c9bc5f179397a45de41bc3",
          "sha1": "68b6603dcfb5689545bc934bb5e99c5d638b8b57",
          "md5": "f7ef824dac6fdfca4aa3c5e82411e3c7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.1.1-SNAPSHOT-sources.jar",
          "size": 49127,
          "sha512": "18ca92fd57137c68d84385de34979fb3cdfd2ab961bb1b6cc42596d6180a2435e4514b9256cc949df3c0feab217bd4c51055248eb357f6744b28e24d7f7b8a34",
          "sha256": "aa8ec9221f88fae1b31ce0c20a21fe2b954631bfd61b8b7695c81d02ee22ef0f",
          "sha1": "e25a84b4bb561012cfbf971b7e3fc6a9add26389",
          "md5": "31807c689d62bf784cd0d793f8d5eba7"
        },
        {
          "name": "dokkatoo-plugin-1.1.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.1.1-SNAPSHOT-sources.jar",
          "size": 49127,
          "sha512": "18ca92fd57137c68d84385de34979fb3cdfd2ab961bb1b6cc42596d6180a2435e4514b9256cc949df3c0feab217bd4c51055248eb357f6744b28e24d7f7b8a34",
          "sha256": "aa8ec9221f88fae1b31ce0c20a21fe2b954631bfd61b8b7695c81d02ee22ef0f",
          "sha1": "e25a84b4bb561012cfbf971b7e3fc6a9add26389",
          "md5": "31807c689d62bf784cd0d793f8d5eba7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.1-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-1.1.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
