{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.2.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.2.1-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.2.1-SNAPSHOT.jar",
          "size": 409587,
          "sha512": "d8db1ffb849fa7b798ee49ffb57f19647b5b283718d624ef4e74414e964f90e2c18ffa3b22f6f8b7d97d1e9f068ea40e9c1ca21eae0acef7ad7c32e316351b03",
          "sha256": "1ce3c2ad9ceb4c452b928b4c06cfe75a65e79a0bc97cbb71dc7e239c5cdcb16b",
          "sha1": "6018c145ffc9e11f1a1c44a6e8796288d0ac7ceb",
          "md5": "188c11c7d71b99371db6bf646fa3b8fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.2.1-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.2.1-SNAPSHOT.jar",
          "size": 409587,
          "sha512": "d8db1ffb849fa7b798ee49ffb57f19647b5b283718d624ef4e74414e964f90e2c18ffa3b22f6f8b7d97d1e9f068ea40e9c1ca21eae0acef7ad7c32e316351b03",
          "sha256": "1ce3c2ad9ceb4c452b928b4c06cfe75a65e79a0bc97cbb71dc7e239c5cdcb16b",
          "sha1": "6018c145ffc9e11f1a1c44a6e8796288d0ac7ceb",
          "md5": "188c11c7d71b99371db6bf646fa3b8fb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.2.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.2.1-SNAPSHOT-sources.jar",
          "size": 50898,
          "sha512": "d15baea66453c30647161875f52c3034ca7bd811cf816fe0470b53656ec1e95e634c1cf8601b2ff482269bbeaf3cd01b0481ae81ae09b1760eac95b293bb9633",
          "sha256": "93d8046b2276f593d2a30f1750a0d4b1f17ee70487db3ca3b318836091656a7e",
          "sha1": "06384dc47ba8661841ece197adfe780a4af3d892",
          "md5": "4a3849d60ee6061537baf90cc64dfcc5"
        },
        {
          "name": "dokkatoo-plugin-1.2.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.2.1-SNAPSHOT-sources.jar",
          "size": 50898,
          "sha512": "d15baea66453c30647161875f52c3034ca7bd811cf816fe0470b53656ec1e95e634c1cf8601b2ff482269bbeaf3cd01b0481ae81ae09b1760eac95b293bb9633",
          "sha256": "93d8046b2276f593d2a30f1750a0d4b1f17ee70487db3ca3b318836091656a7e",
          "sha1": "06384dc47ba8661841ece197adfe780a4af3d892",
          "md5": "4a3849d60ee6061537baf90cc64dfcc5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.2.1-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-1.2.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
