{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.2.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.2.1-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.2.1-SNAPSHOT.jar",
          "size": 409440,
          "sha512": "d48e012d7d603ad4c4318847afb24d4d3b59a87760f7c509cb72f791bb27b9530cdec9ab4118ee6d1585dcfcf18331c6526ea67a19ccb438111b1e3512af67a5",
          "sha256": "08f85855c96023f1af7280c70e3e7345804640bca37816b29c867da6fffcb3cc",
          "sha1": "aa2b540bbe99f4cc9bcf60ff36fcbd4086deae7b",
          "md5": "0a2c33e086900e7f095937d001926d4a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.2.1-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.2.1-SNAPSHOT.jar",
          "size": 409440,
          "sha512": "d48e012d7d603ad4c4318847afb24d4d3b59a87760f7c509cb72f791bb27b9530cdec9ab4118ee6d1585dcfcf18331c6526ea67a19ccb438111b1e3512af67a5",
          "sha256": "08f85855c96023f1af7280c70e3e7345804640bca37816b29c867da6fffcb3cc",
          "sha1": "aa2b540bbe99f4cc9bcf60ff36fcbd4086deae7b",
          "md5": "0a2c33e086900e7f095937d001926d4a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.2.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.2.1-SNAPSHOT-sources.jar",
          "size": 50858,
          "sha512": "ec6a55fe90e265ac22483f8ec7d218a1136351a99236258d4c6baa9c70dc0e74b432510074acff23d8b1a3391fb1b41a94c575849550d9b8dc3587cd6c869084",
          "sha256": "f9eb7e310fd105cead2103d0a3bc923eeb7b2dcaa5c4c6c0b43a3658f8736cb0",
          "sha1": "7092dee2f92fe69caca6045aacff3302354fdba1",
          "md5": "52d61bcac30b96ef09a0a4aac0ce0d93"
        },
        {
          "name": "dokkatoo-plugin-1.2.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.2.1-SNAPSHOT-sources.jar",
          "size": 50858,
          "sha512": "ec6a55fe90e265ac22483f8ec7d218a1136351a99236258d4c6baa9c70dc0e74b432510074acff23d8b1a3391fb1b41a94c575849550d9b8dc3587cd6c869084",
          "sha256": "f9eb7e310fd105cead2103d0a3bc923eeb7b2dcaa5c4c6c0b43a3658f8736cb0",
          "sha1": "7092dee2f92fe69caca6045aacff3302354fdba1",
          "md5": "52d61bcac30b96ef09a0a4aac0ce0d93"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.2.1-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-1.2.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
