{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.0.1-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.0.1-SNAPSHOT.jar",
          "size": 373710,
          "sha512": "982414fe78123c1015f1a1395ec28675ced36507aa44675be77a7aa60644ab4390fb4a2837900615e237ff72038b14907c383cf1ee4ad0c0be48edc838931a1c",
          "sha256": "9e8cd8682f213bcd55e3ead4078f990a261f8b985b47e5fca8ee59b806093167",
          "sha1": "04286bdde2f4dfaa4b43c1ff1750a0563f6074b6",
          "md5": "0cd0541e049b54ea38651581b29f3ae5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.0.1-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.0.1-SNAPSHOT.jar",
          "size": 373710,
          "sha512": "982414fe78123c1015f1a1395ec28675ced36507aa44675be77a7aa60644ab4390fb4a2837900615e237ff72038b14907c383cf1ee4ad0c0be48edc838931a1c",
          "sha256": "9e8cd8682f213bcd55e3ead4078f990a261f8b985b47e5fca8ee59b806093167",
          "sha1": "04286bdde2f4dfaa4b43c1ff1750a0563f6074b6",
          "md5": "0cd0541e049b54ea38651581b29f3ae5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.0.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.0.1-SNAPSHOT-sources.jar",
          "size": 47020,
          "sha512": "986f1bf7e74f988d3bf3142ca80ded3fafe5435276d67cff41898b37f2aba0a5cb35b3c7b62f176ca0d300b2a40229b41b37e3c7fecb34518cd1f693520b899d",
          "sha256": "a0bd0854776c27a1fcfea520b7012f7ae7c520a66be135d83a07bd2c81e953ec",
          "sha1": "2e0bf25b88dc3930509da8dc0046f8cd4b1c3753",
          "md5": "e59b133e5507fee571bbfcd89d30e20e"
        },
        {
          "name": "dokkatoo-plugin-1.0.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.0.1-SNAPSHOT-sources.jar",
          "size": 47020,
          "sha512": "986f1bf7e74f988d3bf3142ca80ded3fafe5435276d67cff41898b37f2aba0a5cb35b3c7b62f176ca0d300b2a40229b41b37e3c7fecb34518cd1f693520b899d",
          "sha256": "a0bd0854776c27a1fcfea520b7012f7ae7c520a66be135d83a07bd2c81e953ec",
          "sha1": "2e0bf25b88dc3930509da8dc0046f8cd4b1c3753",
          "md5": "e59b133e5507fee571bbfcd89d30e20e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.0.1-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-1.0.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
