{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.0.1-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.0.1-SNAPSHOT.jar",
          "size": 387068,
          "sha512": "ba2884ab8c964929dbe4de3eeb0c89fafdf96ea444ec6c58ec58045c2d354e5dfaa393453c3963d5a64cfb0b6c8849c8ed68cc3d164ad6fc7cca7a5008c54cbc",
          "sha256": "c494dc14e574b9c3872daf30a7959e099b2bda4cdb9684fff2aebdc6ceda264a",
          "sha1": "2e48b4f45f726ed93aa2e5fd92ee5581e5f90523",
          "md5": "41f87808d204e1c9000da09236205849"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.0.1-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.0.1-SNAPSHOT.jar",
          "size": 387068,
          "sha512": "ba2884ab8c964929dbe4de3eeb0c89fafdf96ea444ec6c58ec58045c2d354e5dfaa393453c3963d5a64cfb0b6c8849c8ed68cc3d164ad6fc7cca7a5008c54cbc",
          "sha256": "c494dc14e574b9c3872daf30a7959e099b2bda4cdb9684fff2aebdc6ceda264a",
          "sha1": "2e48b4f45f726ed93aa2e5fd92ee5581e5f90523",
          "md5": "41f87808d204e1c9000da09236205849"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.0.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.0.1-SNAPSHOT-sources.jar",
          "size": 48868,
          "sha512": "b076ea3d59adfc2d51fe85c54c2ce29758ec46345be3baf3a29c2ce90cdbd5d3cffeb93660e8bb88e69eedb0ae30621d09429882f024dec1f27c71eab87a07c1",
          "sha256": "cc6f7fd94c15c985ce2876c5191947a510486497e8e0c899544137510e185d90",
          "sha1": "05d219c9d566a60b9cb3a874a956466d48063b14",
          "md5": "79d4c26fd666abaff8a6dc489c57e607"
        },
        {
          "name": "dokkatoo-plugin-1.0.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.0.1-SNAPSHOT-sources.jar",
          "size": 48868,
          "sha512": "b076ea3d59adfc2d51fe85c54c2ce29758ec46345be3baf3a29c2ce90cdbd5d3cffeb93660e8bb88e69eedb0ae30621d09429882f024dec1f27c71eab87a07c1",
          "sha256": "cc6f7fd94c15c985ce2876c5191947a510486497e8e0c899544137510e185d90",
          "sha1": "05d219c9d566a60b9cb3a874a956466d48063b14",
          "md5": "79d4c26fd666abaff8a6dc489c57e607"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.0.1-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-1.0.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
