{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.0.1-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.0.1-SNAPSHOT.jar",
          "size": 386049,
          "sha512": "c7398c2aa08b81c88ace114644655787365107c6adf2de8eba9ce39cda57372baa9607a399d44474732059c3e6bb4ab52932eac12f3f187c347de56699d87b03",
          "sha256": "4b45881ac424b07336a6d6385817f5964fe1f299a512132fc7781423145e60d2",
          "sha1": "b54c25fc0863efc0ccae5ac1d5b901bb9d44b958",
          "md5": "d2cd2b971329c1ccc721ce8fac82d3e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.0.1-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.0.1-SNAPSHOT.jar",
          "size": 386049,
          "sha512": "c7398c2aa08b81c88ace114644655787365107c6adf2de8eba9ce39cda57372baa9607a399d44474732059c3e6bb4ab52932eac12f3f187c347de56699d87b03",
          "sha256": "4b45881ac424b07336a6d6385817f5964fe1f299a512132fc7781423145e60d2",
          "sha1": "b54c25fc0863efc0ccae5ac1d5b901bb9d44b958",
          "md5": "d2cd2b971329c1ccc721ce8fac82d3e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.0.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.0.1-SNAPSHOT-sources.jar",
          "size": 48795,
          "sha512": "731d9fa441dd9cf5e0fb8c71604c0823bca7d9560fcaa9fcf302cc4e9e5de22d343276307902da5ec586804b296424f6d1d16900e60c1d1edd8700eadc39eb20",
          "sha256": "d0e429c1579e0898978aeab7cc8f1f46e3f009a604b3aae3b07b5b4a05ee698b",
          "sha1": "8074231921eff647b12a82f018fc7179342e1bd4",
          "md5": "f825abecaca65e81f8779644bd4367a5"
        },
        {
          "name": "dokkatoo-plugin-1.0.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.0.1-SNAPSHOT-sources.jar",
          "size": 48795,
          "sha512": "731d9fa441dd9cf5e0fb8c71604c0823bca7d9560fcaa9fcf302cc4e9e5de22d343276307902da5ec586804b296424f6d1d16900e60c1d1edd8700eadc39eb20",
          "sha256": "d0e429c1579e0898978aeab7cc8f1f46e3f009a604b3aae3b07b5b4a05ee698b",
          "sha1": "8074231921eff647b12a82f018fc7179342e1bd4",
          "md5": "f825abecaca65e81f8779644bd4367a5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.0.1-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-1.0.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
