{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.0.1-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.0.1-SNAPSHOT.jar",
          "size": 385767,
          "sha512": "2d6c493a8b35b451b3e6faf4402ed68131f544583be0923f8e9d922343b06e51a7b59b74a0aa1df6c7b90505dcb8eb767eacb43e5b8ae0211bf2f6f7013a2a20",
          "sha256": "68b52ad705c01ccf7835bc49a20bd94f61be7f34137ab4151c710dd1ccdae4d7",
          "sha1": "1b5a134cf5d4ab7187746545cf87da9c821544fe",
          "md5": "6048529ef65711be3054058f52d21c42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.0.1-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.0.1-SNAPSHOT.jar",
          "size": 385767,
          "sha512": "2d6c493a8b35b451b3e6faf4402ed68131f544583be0923f8e9d922343b06e51a7b59b74a0aa1df6c7b90505dcb8eb767eacb43e5b8ae0211bf2f6f7013a2a20",
          "sha256": "68b52ad705c01ccf7835bc49a20bd94f61be7f34137ab4151c710dd1ccdae4d7",
          "sha1": "1b5a134cf5d4ab7187746545cf87da9c821544fe",
          "md5": "6048529ef65711be3054058f52d21c42"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.0.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.0.1-SNAPSHOT-sources.jar",
          "size": 49020,
          "sha512": "408e87e37a7b62f418e4df152dca361cf393b4cbced3313d5cdca5afd76334a874b6ec08399cbd53f55a710cf06939f1621aea3a9d8d050d89504f14e1a9f962",
          "sha256": "c9d584f39a933b126b791c0a039bd8d782f2ee8f05ae8edfc10018e7c54c7f46",
          "sha1": "851fa9dbe478aff68f698a6eb8baf8ac98ec5c83",
          "md5": "89cde73b82561b3fc2211dd60f734ca8"
        },
        {
          "name": "dokkatoo-plugin-1.0.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.0.1-SNAPSHOT-sources.jar",
          "size": 49020,
          "sha512": "408e87e37a7b62f418e4df152dca361cf393b4cbced3313d5cdca5afd76334a874b6ec08399cbd53f55a710cf06939f1621aea3a9d8d050d89504f14e1a9f962",
          "sha256": "c9d584f39a933b126b791c0a039bd8d782f2ee8f05ae8edfc10018e7c54c7f46",
          "sha1": "851fa9dbe478aff68f698a6eb8baf8ac98ec5c83",
          "md5": "89cde73b82561b3fc2211dd60f734ca8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.0.1-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-1.0.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
