{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0.jar",
          "url": "dokkatoo-plugin-1.4.0.jar",
          "size": 409491,
          "sha512": "326ad35681eeb5eccfdd053df8cc53e5e223421d3bcd21de2d2dc46c4888adf0a18cbac9a70f04ebbaf683ffac1e6b16d8969d8a62135d38067690f80efe8ac7",
          "sha256": "1e6523f238157c57ee707eccec766aade2ce7c4243d1b0cf74632a581cceca6c",
          "sha1": "ede1cc78067d085d38ab005043d17af161d984c5",
          "md5": "95204e5e13742763ea22d760cf7c3783"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0.jar",
          "url": "dokkatoo-plugin-1.4.0.jar",
          "size": 409491,
          "sha512": "326ad35681eeb5eccfdd053df8cc53e5e223421d3bcd21de2d2dc46c4888adf0a18cbac9a70f04ebbaf683ffac1e6b16d8969d8a62135d38067690f80efe8ac7",
          "sha256": "1e6523f238157c57ee707eccec766aade2ce7c4243d1b0cf74632a581cceca6c",
          "sha1": "ede1cc78067d085d38ab005043d17af161d984c5",
          "md5": "95204e5e13742763ea22d760cf7c3783"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-sources.jar",
          "url": "dokkatoo-plugin-1.4.0-sources.jar",
          "size": 59132,
          "sha512": "e931afed919473483e8d9da84b5a3419836afaf2826625d7608d565413bdada71424a2a2725b1504a5dd23c47e35f1d7a918a50a343beeb27527bd44c0fc48a7",
          "sha256": "ca772ee1d1eb77666b5c96c430954a57db2121ec93b6fcda3f38e8b2c1272286",
          "sha1": "dfeb815e656fcd8e2e9ecc9c370859d99628062f",
          "md5": "90c529cfc3a009fe692fb3e13a573206"
        },
        {
          "name": "dokkatoo-plugin-1.4.0-sources.jar",
          "url": "dokkatoo-plugin-1.4.0-sources.jar",
          "size": 59132,
          "sha512": "e931afed919473483e8d9da84b5a3419836afaf2826625d7608d565413bdada71424a2a2725b1504a5dd23c47e35f1d7a918a50a343beeb27527bd44c0fc48a7",
          "sha256": "ca772ee1d1eb77666b5c96c430954a57db2121ec93b6fcda3f38e8b2c1272286",
          "sha1": "dfeb815e656fcd8e2e9ecc9c370859d99628062f",
          "md5": "90c529cfc3a009fe692fb3e13a573206"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-javadoc.jar",
          "url": "dokkatoo-plugin-1.4.0-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
