{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-0.0.1-SNAPSHOT.jar",
          "url": "dokkatoo-0.0.1-SNAPSHOT.jar",
          "size": 278925,
          "sha512": "1ece71531101bac27500fc26e6785210c0d2d14ac1f288b61668db6b5ffa21367840e600a73921c54497558d4d905cce5980970e92a200a7c45b79ddbcb13bf1",
          "sha256": "2ca111927aa65cf68ccb396d7af6ae12673680c0ca79e5b3d0a74ce916463c48",
          "sha1": "a76d7520e106580cdc9b001c85f15deb53184161",
          "md5": "58cc32c671c4938cfc290d9fb05ffa29"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "dokkatoo-0.0.1-SNAPSHOT.jar",
          "url": "dokkatoo-0.0.1-SNAPSHOT.jar",
          "size": 278925,
          "sha512": "1ece71531101bac27500fc26e6785210c0d2d14ac1f288b61668db6b5ffa21367840e600a73921c54497558d4d905cce5980970e92a200a7c45b79ddbcb13bf1",
          "sha256": "2ca111927aa65cf68ccb396d7af6ae12673680c0ca79e5b3d0a74ce916463c48",
          "sha1": "a76d7520e106580cdc9b001c85f15deb53184161",
          "md5": "58cc32c671c4938cfc290d9fb05ffa29"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.adamko.dokkatoo",
          "module": "dokkatoo",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "dokkatoo-0.0.1-SNAPSHOT-test-fixtures.jar",
          "url": "dokkatoo-0.0.1-SNAPSHOT-test-fixtures.jar",
          "size": 22135,
          "sha512": "c5096561507f90b3d0d78a3a7684ef3e433920a3dc2199bb1b669e86fca18fa1183f353c018de5d5cc7a2b2b8c989afd5521d0e1cf558acf04029352e1f319b8",
          "sha256": "d84bff79a71716cf37f6ebc2c3ef22fe683cd028608c8e16d859397e9e7f5ab0",
          "sha1": "d4c00ed309a4f5e1c5f874a608bad4f2fab686e7",
          "md5": "a7160324b73e1882d6d11c643035bd29"
        }
      ],
      "capabilities": [
        {
          "group": "dev.adamko.dokkatoo",
          "name": "dokkatoo-base-plugin-test-fixtures",
          "version": "0.0.1-SNAPSHOT"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "dev.adamko.dokkatoo",
          "module": "dokkatoo",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "dokkatoo-0.0.1-SNAPSHOT-test-fixtures.jar",
          "url": "dokkatoo-0.0.1-SNAPSHOT-test-fixtures.jar",
          "size": 22135,
          "sha512": "c5096561507f90b3d0d78a3a7684ef3e433920a3dc2199bb1b669e86fca18fa1183f353c018de5d5cc7a2b2b8c989afd5521d0e1cf558acf04029352e1f319b8",
          "sha256": "d84bff79a71716cf37f6ebc2c3ef22fe683cd028608c8e16d859397e9e7f5ab0",
          "sha1": "d4c00ed309a4f5e1c5f874a608bad4f2fab686e7",
          "md5": "a7160324b73e1882d6d11c643035bd29"
        }
      ],
      "capabilities": [
        {
          "group": "dev.adamko.dokkatoo",
          "name": "dokkatoo-base-plugin-test-fixtures",
          "version": "0.0.1-SNAPSHOT"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-0.0.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-0.0.1-SNAPSHOT-sources.jar",
          "size": 35816,
          "sha512": "87d6a22f863363f83956faa53904744cfc40947fe18912531a775020d39a59b9a3e7d42ce47bce3b0c09ab3b10f858b2b7cafa235fca3c0b75316a9e9eea1641",
          "sha256": "5d50ee63b14e5cf85e20c028ef261fd6458aa45a58e2e653c7ae994623233265",
          "sha1": "60e3fc54fe6f2297be30f44b97adf4b339c8177d",
          "md5": "4db7549b59898f9a8e063698052f4d2d"
        },
        {
          "name": "dokkatoo-0.0.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-0.0.1-SNAPSHOT-sources.jar",
          "size": 35816,
          "sha512": "87d6a22f863363f83956faa53904744cfc40947fe18912531a775020d39a59b9a3e7d42ce47bce3b0c09ab3b10f858b2b7cafa235fca3c0b75316a9e9eea1641",
          "sha256": "5d50ee63b14e5cf85e20c028ef261fd6458aa45a58e2e653c7ae994623233265",
          "sha1": "60e3fc54fe6f2297be30f44b97adf4b339c8177d",
          "md5": "4db7549b59898f9a8e063698052f4d2d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-0.0.1-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-0.0.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
