{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-0.0.1-SNAPSHOT.jar",
          "url": "dokkatoo-0.0.1-SNAPSHOT.jar",
          "size": 323627,
          "sha512": "d2bdf834eb4f2f2ffe5507efecc2e04483499fff677b2310d95c62c5d23291f8e5d64e3e113641f0330c35e9af31dff4a8c373271a44e906131e16981550e98f",
          "sha256": "eab63a696fb00939dcf2349a8c2c4e5e868fdcbd034b67e3a9a7cb86ecd71b67",
          "sha1": "2fde2232516f1e29dd68ecb9b4269045664925a6",
          "md5": "3263d1118bdff8cd59a5fe9b92ad3b42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "dokkatoo-0.0.1-SNAPSHOT.jar",
          "url": "dokkatoo-0.0.1-SNAPSHOT.jar",
          "size": 323627,
          "sha512": "d2bdf834eb4f2f2ffe5507efecc2e04483499fff677b2310d95c62c5d23291f8e5d64e3e113641f0330c35e9af31dff4a8c373271a44e906131e16981550e98f",
          "sha256": "eab63a696fb00939dcf2349a8c2c4e5e868fdcbd034b67e3a9a7cb86ecd71b67",
          "sha1": "2fde2232516f1e29dd68ecb9b4269045664925a6",
          "md5": "3263d1118bdff8cd59a5fe9b92ad3b42"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-0.0.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-0.0.1-SNAPSHOT-sources.jar",
          "size": 38271,
          "sha512": "9812856c72c5b03abde26085505e5223732519337d21187b2a646ece253a837ca9003b973399e9e58b946f62f447a2318231172fed8d70510231977d968f5d45",
          "sha256": "8241b96726c3b4d40c1efb221c6fe0ef5ec5c3d484a4cb9504f3754b3ebb309c",
          "sha1": "90042dc7aae5fe4d0183dbc6d93d9561a55ededb",
          "md5": "38c4a458b1983faaeb8df89e7be67a5d"
        },
        {
          "name": "dokkatoo-0.0.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-0.0.1-SNAPSHOT-sources.jar",
          "size": 38271,
          "sha512": "9812856c72c5b03abde26085505e5223732519337d21187b2a646ece253a837ca9003b973399e9e58b946f62f447a2318231172fed8d70510231977d968f5d45",
          "sha256": "8241b96726c3b4d40c1efb221c6fe0ef5ec5c3d484a4cb9504f3754b3ebb309c",
          "sha1": "90042dc7aae5fe4d0183dbc6d93d9561a55ededb",
          "md5": "38c4a458b1983faaeb8df89e7be67a5d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-0.0.1-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-0.0.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
