{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-0.0.1-SNAPSHOT.jar",
          "url": "dokkatoo-0.0.1-SNAPSHOT.jar",
          "size": 286429,
          "sha512": "c2c253933ed6da5026ff516e679baa8454054e09b9cbcc6ade7ca82c0ab1e06a75e8909c0911c9ea3d77a38b037f2d6a4f77943bedd4d4db36f7d7e0a4f2e62e",
          "sha256": "426ac4a801c18062dd97c813a336cc39360682b94914b1e25028af42e847b346",
          "sha1": "032ef666837f4bfa9bf4b7abd97a298eeb32242c",
          "md5": "09300e90d71c068b05596595c559042f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "dokkatoo-0.0.1-SNAPSHOT.jar",
          "url": "dokkatoo-0.0.1-SNAPSHOT.jar",
          "size": 286429,
          "sha512": "c2c253933ed6da5026ff516e679baa8454054e09b9cbcc6ade7ca82c0ab1e06a75e8909c0911c9ea3d77a38b037f2d6a4f77943bedd4d4db36f7d7e0a4f2e62e",
          "sha256": "426ac4a801c18062dd97c813a336cc39360682b94914b1e25028af42e847b346",
          "sha1": "032ef666837f4bfa9bf4b7abd97a298eeb32242c",
          "md5": "09300e90d71c068b05596595c559042f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-0.0.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-0.0.1-SNAPSHOT-sources.jar",
          "size": 37053,
          "sha512": "1dbb07cf05aa44c090bd2a708df686db7c48acdd29c67da06f156538318c2696f516b2fe50425731ec0377aa4a54e5fc1eb8e1635d6eec88d281bdcfbaa2529b",
          "sha256": "ccf2358ca02128751bbc09997e377777b237848cbe195673e505dbef5f37065b",
          "sha1": "3ae2a4cfea3f527aa8ccf9fb46eb45afc67635dd",
          "md5": "8dc2091c35e491ef11bff57d3aeacd16"
        },
        {
          "name": "dokkatoo-0.0.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-0.0.1-SNAPSHOT-sources.jar",
          "size": 37053,
          "sha512": "1dbb07cf05aa44c090bd2a708df686db7c48acdd29c67da06f156538318c2696f516b2fe50425731ec0377aa4a54e5fc1eb8e1635d6eec88d281bdcfbaa2529b",
          "sha256": "ccf2358ca02128751bbc09997e377777b237848cbe195673e505dbef5f37065b",
          "sha1": "3ae2a4cfea3f527aa8ccf9fb46eb45afc67635dd",
          "md5": "8dc2091c35e491ef11bff57d3aeacd16"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-0.0.1-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-0.0.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
