{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.3.0-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.3.0-SNAPSHOT.jar",
          "size": 442822,
          "sha512": "e05b3b185549ae1cf7908fae633b2d9323fef195dd0550df866e6ac81c75803ecd571cf67a699e6a621c5e2db4bc57820cb908af418d446a555bb65ac1b7d29a",
          "sha256": "9f9d07e2b2631a47f7f767cde3f059fde0aa4aa54e3f11c8d8167f827d2603e7",
          "sha1": "af703a45eb9fa2a4e143d7ab7945b1c0b657cff2",
          "md5": "43f079adecb6ee06f8111b74c0f8137f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.3.0-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.3.0-SNAPSHOT.jar",
          "size": 442822,
          "sha512": "e05b3b185549ae1cf7908fae633b2d9323fef195dd0550df866e6ac81c75803ecd571cf67a699e6a621c5e2db4bc57820cb908af418d446a555bb65ac1b7d29a",
          "sha256": "9f9d07e2b2631a47f7f767cde3f059fde0aa4aa54e3f11c8d8167f827d2603e7",
          "sha1": "af703a45eb9fa2a4e143d7ab7945b1c0b657cff2",
          "md5": "43f079adecb6ee06f8111b74c0f8137f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.3.0-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.3.0-SNAPSHOT-sources.jar",
          "size": 54214,
          "sha512": "dd2e7da3633d08e7a0c7bad0c90d22d4423fed66ee1d85c2e5165d9a0027cada5798d3984d9765a67b37e085a4f5d1f0f857acb98879e68413b33056b0ca234a",
          "sha256": "20e4506f0e532a590ac9ff0184ffc9716743d5951abf00423dd0b585bfaa4af6",
          "sha1": "d1800e5490fdea6e698dbc6a19859ecf8bbd2e09",
          "md5": "40fb6150e323bc7e8dc657a26689843b"
        },
        {
          "name": "dokkatoo-plugin-1.3.0-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.3.0-SNAPSHOT-sources.jar",
          "size": 54214,
          "sha512": "dd2e7da3633d08e7a0c7bad0c90d22d4423fed66ee1d85c2e5165d9a0027cada5798d3984d9765a67b37e085a4f5d1f0f857acb98879e68413b33056b0ca234a",
          "sha256": "20e4506f0e532a590ac9ff0184ffc9716743d5951abf00423dd0b585bfaa4af6",
          "sha1": "d1800e5490fdea6e698dbc6a19859ecf8bbd2e09",
          "md5": "40fb6150e323bc7e8dc657a26689843b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.3.0-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-1.3.0-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
