{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.1-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-0.0.1-SNAPSHOT.jar",
          "size": 336715,
          "sha512": "6cacbe7a7e47d8120def0d00877c947b124a2ec26422fd5a745e151b61ef7f8509faa5fbd3604fe5432b6f4d71cf41cd971b438bc441bedaacf241448a767a14",
          "sha256": "61f3d3e13b1abe1254e41d8ae2c2a98fccfc0193580578cfc2af8c71c4f01937",
          "sha1": "1a5e53cfab20fa0f2f1017553231d955a5a8ac1c",
          "md5": "8ef8010ea2aeaf54a2b23a2fdd588e47"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.1-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-0.0.1-SNAPSHOT.jar",
          "size": 336715,
          "sha512": "6cacbe7a7e47d8120def0d00877c947b124a2ec26422fd5a745e151b61ef7f8509faa5fbd3604fe5432b6f4d71cf41cd971b438bc441bedaacf241448a767a14",
          "sha256": "61f3d3e13b1abe1254e41d8ae2c2a98fccfc0193580578cfc2af8c71c4f01937",
          "sha1": "1a5e53cfab20fa0f2f1017553231d955a5a8ac1c",
          "md5": "8ef8010ea2aeaf54a2b23a2fdd588e47"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.1-SNAPSHOT-sources.jar",
          "size": 38626,
          "sha512": "6d0bc5d9a11d92ddd50d56b48da3fe53fdf6166c265b97ccbe13ac92b94410e18b32b3eb84508e5a6cec3fc101bad1e78b0ff091e6ca4db21601aa4e905a6767",
          "sha256": "c61f30d38ddef3755a502b836e1d5292cf6a495abf8f733ca398065eba636684",
          "sha1": "decd1888f01e22ad21b0b6d7803fe140ebd5080c",
          "md5": "3b1376cf3b63f5edc44a436f758fd800"
        },
        {
          "name": "dokkatoo-plugin-0.0.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.1-SNAPSHOT-sources.jar",
          "size": 38626,
          "sha512": "6d0bc5d9a11d92ddd50d56b48da3fe53fdf6166c265b97ccbe13ac92b94410e18b32b3eb84508e5a6cec3fc101bad1e78b0ff091e6ca4db21601aa4e905a6767",
          "sha256": "c61f30d38ddef3755a502b836e1d5292cf6a495abf8f733ca398065eba636684",
          "sha1": "decd1888f01e22ad21b0b6d7803fe140ebd5080c",
          "md5": "3b1376cf3b63f5edc44a436f758fd800"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.1-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-0.0.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
