{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.1-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-0.0.1-SNAPSHOT.jar",
          "size": 342797,
          "sha512": "2c2a241b77bad684e2f8ff45541f5da9282aaefbb0cc06873103b9e8e58479a9e1b5c398a98b7d7cab8241b13c4e674f226eec242ae379bfbdd70736fc0ea40f",
          "sha256": "170568eb3d09ea9d5e0a956a12718a6bbc467045805b13bf05b1225d14736ba1",
          "sha1": "42bd153ff327c3d6df2d570d21d4d3c2e22694f7",
          "md5": "39a5b77281c594da84bd1fa42f861f28"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.1-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-0.0.1-SNAPSHOT.jar",
          "size": 342797,
          "sha512": "2c2a241b77bad684e2f8ff45541f5da9282aaefbb0cc06873103b9e8e58479a9e1b5c398a98b7d7cab8241b13c4e674f226eec242ae379bfbdd70736fc0ea40f",
          "sha256": "170568eb3d09ea9d5e0a956a12718a6bbc467045805b13bf05b1225d14736ba1",
          "sha1": "42bd153ff327c3d6df2d570d21d4d3c2e22694f7",
          "md5": "39a5b77281c594da84bd1fa42f861f28"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.1-SNAPSHOT-sources.jar",
          "size": 38770,
          "sha512": "de4ff8302011866d281519f2884da33278cc1aa12c03d9ec0cbec4eadccc61fc943ccf77e069beada72ba43706fd5ef3fe794cb216298d7f5e8cac829ad3289a",
          "sha256": "404b801a0355a10ad23dbb09f65824b9598e6e85b892854c8cb4b25b956b1e82",
          "sha1": "b19d2bddad770cf0c7949de78d15d52b6fb52cd2",
          "md5": "b128169291d636ce176eaff9f5d2dc01"
        },
        {
          "name": "dokkatoo-plugin-0.0.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.1-SNAPSHOT-sources.jar",
          "size": 38770,
          "sha512": "de4ff8302011866d281519f2884da33278cc1aa12c03d9ec0cbec4eadccc61fc943ccf77e069beada72ba43706fd5ef3fe794cb216298d7f5e8cac829ad3289a",
          "sha256": "404b801a0355a10ad23dbb09f65824b9598e6e85b892854c8cb4b25b956b1e82",
          "sha1": "b19d2bddad770cf0c7949de78d15d52b6fb52cd2",
          "md5": "b128169291d636ce176eaff9f5d2dc01"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.1-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-0.0.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
