{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "0.0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.5-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-0.0.5-SNAPSHOT.jar",
          "size": 322500,
          "sha512": "21fb398aa5a5bb1a3480231cc25c22076d8887e9d8be8839658cbfa8606a72b86dfa896fe4cb87527a2b5fd4a7c63153d259fed07ab742e02d9f10f48a9266fd",
          "sha256": "d1034b9b7266ef4f49eb236a93d5807bd5534f9b46e9e901059f18bfaecab2fc",
          "sha1": "86908b290e5800bd1c1514c334f1da751d59fe53",
          "md5": "7883af5eab175e9f8a3b3777c24dcf97"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.5-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-0.0.5-SNAPSHOT.jar",
          "size": 322500,
          "sha512": "21fb398aa5a5bb1a3480231cc25c22076d8887e9d8be8839658cbfa8606a72b86dfa896fe4cb87527a2b5fd4a7c63153d259fed07ab742e02d9f10f48a9266fd",
          "sha256": "d1034b9b7266ef4f49eb236a93d5807bd5534f9b46e9e901059f18bfaecab2fc",
          "sha1": "86908b290e5800bd1c1514c334f1da751d59fe53",
          "md5": "7883af5eab175e9f8a3b3777c24dcf97"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.5-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.5-SNAPSHOT-sources.jar",
          "size": 38636,
          "sha512": "eceac28a7e2b7890c89ee4b10ed526fc13c1942eb13adf2890b5c0d96873d0635ad056a12345f0c34a79e75de3a7548f73cca8047b06ee31402d901ea4e29275",
          "sha256": "5cd6e5387f8ce43602341194f9f225cfaf2d12f71805e8d7d4a6914299b2952d",
          "sha1": "5da3e97613b790b6b21d0d31ece25ea2e9a3624d",
          "md5": "03e83fc24afa00ba0b0c18dfd5d4d40c"
        },
        {
          "name": "dokkatoo-plugin-0.0.5-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.5-SNAPSHOT-sources.jar",
          "size": 38636,
          "sha512": "eceac28a7e2b7890c89ee4b10ed526fc13c1942eb13adf2890b5c0d96873d0635ad056a12345f0c34a79e75de3a7548f73cca8047b06ee31402d901ea4e29275",
          "sha256": "5cd6e5387f8ce43602341194f9f225cfaf2d12f71805e8d7d4a6914299b2952d",
          "sha1": "5da3e97613b790b6b21d0d31ece25ea2e9a3624d",
          "md5": "03e83fc24afa00ba0b0c18dfd5d4d40c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.5-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-0.0.5-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
