{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "0.0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.5-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-0.0.5-SNAPSHOT.jar",
          "size": 322473,
          "sha512": "4e133112c83425d47e1517bc85273fad8d994a5376cf0bbcb697bd52a3a4e8e02d15ec190fd745d736b892d40afb37e7b01f51ea0237c8040604af59d86b5804",
          "sha256": "54ddcb8d40aa18d945276e1e892c6a488018a1df81073b459d50b8dfa6357ca4",
          "sha1": "05389a2a119008ad55fa2462e41a7e08a432f25c",
          "md5": "650da71ad102449c8bea193ddf00781b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.5-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-0.0.5-SNAPSHOT.jar",
          "size": 322473,
          "sha512": "4e133112c83425d47e1517bc85273fad8d994a5376cf0bbcb697bd52a3a4e8e02d15ec190fd745d736b892d40afb37e7b01f51ea0237c8040604af59d86b5804",
          "sha256": "54ddcb8d40aa18d945276e1e892c6a488018a1df81073b459d50b8dfa6357ca4",
          "sha1": "05389a2a119008ad55fa2462e41a7e08a432f25c",
          "md5": "650da71ad102449c8bea193ddf00781b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.5-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.5-SNAPSHOT-sources.jar",
          "size": 38634,
          "sha512": "ad6ab7c3ba764d04feb5d8d10dd30386f329c41c248ac21c3e4da460c59a7c325fb10fa816edf5fc621441431ca6bc02ba9dba384aba53e43c9d265b6f4ee932",
          "sha256": "3a6e1880142e5b9e752895ab09cfe1e5b215968e4672eb0d884a3b9884de7b92",
          "sha1": "ef09f0ba125eb05ac59a2e7ad807f73cb29a8a05",
          "md5": "8fe469d13f5a30c1ea721af278389c86"
        },
        {
          "name": "dokkatoo-plugin-0.0.5-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.5-SNAPSHOT-sources.jar",
          "size": 38634,
          "sha512": "ad6ab7c3ba764d04feb5d8d10dd30386f329c41c248ac21c3e4da460c59a7c325fb10fa816edf5fc621441431ca6bc02ba9dba384aba53e43c9d265b6f4ee932",
          "sha256": "3a6e1880142e5b9e752895ab09cfe1e5b215968e4672eb0d884a3b9884de7b92",
          "sha1": "ef09f0ba125eb05ac59a2e7ad807f73cb29a8a05",
          "md5": "8fe469d13f5a30c1ea721af278389c86"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.5-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-0.0.5-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
