{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "0.0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.5-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-0.0.5-SNAPSHOT.jar",
          "size": 373711,
          "sha512": "453d5bd1e493bb271910bf0f8a353f9b933e174caf3b82019bb2a0a3c00ecb7668e90267e497ca5086220aaa1a44e6f4cb9009ab8f988fe97901fcece6f61655",
          "sha256": "c75614e1ab0ed374ac39dd47c171d761ff3402175e73a372359fc944e181a705",
          "sha1": "a1f815b5e041cd74b5592725e76cfe1b73bf2a79",
          "md5": "56bf7d51159814fd89a2676d527484e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.5-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-0.0.5-SNAPSHOT.jar",
          "size": 373711,
          "sha512": "453d5bd1e493bb271910bf0f8a353f9b933e174caf3b82019bb2a0a3c00ecb7668e90267e497ca5086220aaa1a44e6f4cb9009ab8f988fe97901fcece6f61655",
          "sha256": "c75614e1ab0ed374ac39dd47c171d761ff3402175e73a372359fc944e181a705",
          "sha1": "a1f815b5e041cd74b5592725e76cfe1b73bf2a79",
          "md5": "56bf7d51159814fd89a2676d527484e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.5-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.5-SNAPSHOT-sources.jar",
          "size": 47022,
          "sha512": "87bdea31c1989dfee5b79ea98e22e27abf28cbc53abbc2f7027507ee37fb0034b08183ad3e337f01c8b03ecb62bcb1a6232b7c37557512e68a195c8fd1d0a1fb",
          "sha256": "e862ec62fea9247236017ef7789e721ffd3aaf3a571cd5c7e74607546318c765",
          "sha1": "71fb263cdc59b5edc1dcbf3c2d8192fd6d271fe2",
          "md5": "8df1c0ed3873cbae3990ea36e025da4c"
        },
        {
          "name": "dokkatoo-plugin-0.0.5-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.5-SNAPSHOT-sources.jar",
          "size": 47022,
          "sha512": "87bdea31c1989dfee5b79ea98e22e27abf28cbc53abbc2f7027507ee37fb0034b08183ad3e337f01c8b03ecb62bcb1a6232b7c37557512e68a195c8fd1d0a1fb",
          "sha256": "e862ec62fea9247236017ef7789e721ffd3aaf3a571cd5c7e74607546318c765",
          "sha1": "71fb263cdc59b5edc1dcbf3c2d8192fd6d271fe2",
          "md5": "8df1c0ed3873cbae3990ea36e025da4c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.5-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-0.0.5-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
