{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "0.0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.5-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-0.0.5-SNAPSHOT.jar",
          "size": 322514,
          "sha512": "66bb8dffb2ffa7226368c6bd73d8a4481ae21dd573ec6ba082cb845de891574a4cdab7b34b2644baa3745abd95a3e6e38389bec4576479e352da25dbc6bb5124",
          "sha256": "aac027a0baaf95c169843f8501fcb6e74963c0abb4dffd42621f547554200ecf",
          "sha1": "c182a79a0ed28c259436c717adb6145717d13068",
          "md5": "68e43b800883eb4ea491b6057adbb941"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.5-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-0.0.5-SNAPSHOT.jar",
          "size": 322514,
          "sha512": "66bb8dffb2ffa7226368c6bd73d8a4481ae21dd573ec6ba082cb845de891574a4cdab7b34b2644baa3745abd95a3e6e38389bec4576479e352da25dbc6bb5124",
          "sha256": "aac027a0baaf95c169843f8501fcb6e74963c0abb4dffd42621f547554200ecf",
          "sha1": "c182a79a0ed28c259436c717adb6145717d13068",
          "md5": "68e43b800883eb4ea491b6057adbb941"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.5-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.5-SNAPSHOT-sources.jar",
          "size": 38645,
          "sha512": "c1fbe4ce522e5aa6675fa9106fb41333dfee5e9043d132aa114bd93837d21fc44beaa65a235137e6f13c55f88c51aba4670d7af74cb9fe531b6ccff94dbdeae2",
          "sha256": "d34e8f55483edf7211a2d4b98b9c8d2d2071af3f814c92500b948fd73d2358b6",
          "sha1": "077a69a0e344b8de51a0b11f3e05c431c89b8f83",
          "md5": "63f1c657227b38c257c024722a443833"
        },
        {
          "name": "dokkatoo-plugin-0.0.5-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.5-SNAPSHOT-sources.jar",
          "size": 38645,
          "sha512": "c1fbe4ce522e5aa6675fa9106fb41333dfee5e9043d132aa114bd93837d21fc44beaa65a235137e6f13c55f88c51aba4670d7af74cb9fe531b6ccff94dbdeae2",
          "sha256": "d34e8f55483edf7211a2d4b98b9c8d2d2071af3f814c92500b948fd73d2358b6",
          "sha1": "077a69a0e344b8de51a0b11f3e05c431c89b8f83",
          "md5": "63f1c657227b38c257c024722a443833"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.5-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-0.0.5-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
