package buildsrc.conventions

import org.gradle.internal.fingerprint.IgnoredPathInputNormalizer
import org.jetbrains.kotlin.util.suffixIfNot


/**
 * Utilities for preparing Android projects
 */

plugins {
  base
  id("buildsrc.conventions.base")
}


val androidSdkDir: Provider<File> = providers
  // first try getting the SDK installed on via GitHub step setup-android
  .environmentVariable("ANDROID_SDK_ROOT").map(::File)
  // else get the project-local SDK
  .orElse(layout.projectDirectory.file("projects/ANDROID_SDK").asFile)


val createAndroidLocalPropertiesFile by tasks.registering {

  val localPropertiesFile = temporaryDir.resolve("local.properties")
  outputs.file(localPropertiesFile).withPropertyName("localPropertiesFile")

  val androidSdkDir = androidSdkDir
  inputs.file(androidSdkDir)
    .withPropertyName("androidSdkDir")
    .withNormalizer(IgnoredPathInputNormalizer::class)

  doLast {
    val androidSdkPath = androidSdkDir.get().invariantSeparatorsPath

    localPropertiesFile.apply {
      parentFile.mkdirs()
      createNewFile()
      writeText(
        """
          |# DO NOT EDIT - Generated by $path
          |
          |sdk.dir=$androidSdkPath
          |
        """.trimMargin()
      )
    }
  }
}


val updateAndroidLocalProperties by tasks.registering {

  // find all local.properties files
  val localPropertiesFiles = layout.projectDirectory.dir("projects")
    .asFileTree
    .matching { include("**/local.properties") }
    .files

  outputs.files(localPropertiesFiles).withPropertyName("localPropertiesFiles")

  val androidSdkDir = androidSdkDir
  inputs.file(androidSdkDir)
    .withPropertyName("androidSdkDir")
    .withNormalizer(IgnoredPathInputNormalizer::class)

  doLast {
    val androidSdkDirPath = androidSdkDir.get().invariantSeparatorsPath

    localPropertiesFiles
      .filter { it.exists() }
      .forEach { file ->
        file.writeText(
          file.useLines { lines ->
            lines.joinToString("\n") { line ->
              when {
                line.startsWith("sdk.dir=") -> "sdk.dir=$androidSdkDirPath"
                else                        -> line
              }
            }.suffixIfNot("\n")
          }
        )
      }
  }
}
