{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-2.0.0-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-2.0.0-SNAPSHOT.jar",
          "size": 408968,
          "sha512": "f3eea941aea0a2e8ed4185cbaf92d4065bfa62bce9ac02b3f07cd75f7449bc19e39821bedd9c817585e028cf40790fddc0cdb19f4b324d801a3dc9d046635e15",
          "sha256": "198ea5a2160c526d6f2437e1cb200fa95b2a222ffebd76fe007c7a0a246042e6",
          "sha1": "ccdbad54cc65322262fbc8888b61ccd3ad12a5e2",
          "md5": "98e5ad9beaaf6e707da938b71e461bad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-2.0.0-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-2.0.0-SNAPSHOT.jar",
          "size": 408968,
          "sha512": "f3eea941aea0a2e8ed4185cbaf92d4065bfa62bce9ac02b3f07cd75f7449bc19e39821bedd9c817585e028cf40790fddc0cdb19f4b324d801a3dc9d046635e15",
          "sha256": "198ea5a2160c526d6f2437e1cb200fa95b2a222ffebd76fe007c7a0a246042e6",
          "sha1": "ccdbad54cc65322262fbc8888b61ccd3ad12a5e2",
          "md5": "98e5ad9beaaf6e707da938b71e461bad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-2.0.0-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-2.0.0-SNAPSHOT-sources.jar",
          "size": 58868,
          "sha512": "ed71d494568bcd5284ae075a9b268431de8ac1ff537627eea940412d8a45688ebb9f1235cc0896f7502b0149a7d7488026a41eb06db4824a7b2f4692bb1b779f",
          "sha256": "f3d2efb44a0bc991727f7e845a6892cf692fc9a6c2bb159453d0b0a9841a7784",
          "sha1": "3c95a6e76f1834b02f56bd98512c07ad882d8140",
          "md5": "4824660ecdb932cbcdf0a383a69a650a"
        },
        {
          "name": "dokkatoo-plugin-2.0.0-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-2.0.0-SNAPSHOT-sources.jar",
          "size": 58868,
          "sha512": "ed71d494568bcd5284ae075a9b268431de8ac1ff537627eea940412d8a45688ebb9f1235cc0896f7502b0149a7d7488026a41eb06db4824a7b2f4692bb1b779f",
          "sha256": "f3d2efb44a0bc991727f7e845a6892cf692fc9a6c2bb159453d0b0a9841a7784",
          "sha1": "3c95a6e76f1834b02f56bd98512c07ad882d8140",
          "md5": "4824660ecdb932cbcdf0a383a69a650a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-2.0.0-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-2.0.0-SNAPSHOT-javadoc.jar",
          "size": 463,
          "sha512": "f99717611fb37ef46a7a04f3aeaf6357dde79e1e33227972b33842aaf617ff31bad9250cf17d5f0305d829e93c4b15ff033c7a7e74c54659baddf8d5f5f00ef8",
          "sha256": "039041afafe3bedfb4e9401dffc821d49345af56ab514f96ff8c6def55982dc1",
          "sha1": "62b2749848f767b3d73151761d54e56ce542cac6",
          "md5": "c12c4f98e92c4760058812e7a8630d20"
        }
      ]
    }
  ]
}
