{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT.jar",
          "size": 463851,
          "sha512": "d93f246bd23700f0bfff400a30d6b7eb783ed897a0b4aa17de25a3549a8679be844e3eab4e5e0c1f9956a8a5b4532d38c496442a508525d048d1f34e7a237de1",
          "sha256": "d39ef9c86f1e6136424139dadd3df7e9178035ae1d85cb8d7cc05178a6b85f4f",
          "sha1": "30716c23e22db901d053097b4900b0ab5e90af9d",
          "md5": "0eff5afe54194fa56f7d4ef70aef6be8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT.jar",
          "size": 463851,
          "sha512": "d93f246bd23700f0bfff400a30d6b7eb783ed897a0b4aa17de25a3549a8679be844e3eab4e5e0c1f9956a8a5b4532d38c496442a508525d048d1f34e7a237de1",
          "sha256": "d39ef9c86f1e6136424139dadd3df7e9178035ae1d85cb8d7cc05178a6b85f4f",
          "sha1": "30716c23e22db901d053097b4900b0ab5e90af9d",
          "md5": "0eff5afe54194fa56f7d4ef70aef6be8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT-sources.jar",
          "size": 55213,
          "sha512": "3b42db8b8a622a0997ab60f884e283b91d922b13c4f041a91d9f8c6586763dc8b5d025a100bc766d705fad1842855068e21f88440b86ca1add186bada7aac00a",
          "sha256": "1800a327e60024cbf109f7fc4f686a1a17f52a9a565e8754fb66c7936704f497",
          "sha1": "4d3402c59dd67f387ecdf974c319635db0d1d460",
          "md5": "b9d7fdfde842899366155129caf50c9b"
        },
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT-sources.jar",
          "size": 55213,
          "sha512": "3b42db8b8a622a0997ab60f884e283b91d922b13c4f041a91d9f8c6586763dc8b5d025a100bc766d705fad1842855068e21f88440b86ca1add186bada7aac00a",
          "sha256": "1800a327e60024cbf109f7fc4f686a1a17f52a9a565e8754fb66c7936704f497",
          "sha1": "4d3402c59dd67f387ecdf974c319635db0d1d460",
          "md5": "b9d7fdfde842899366155129caf50c9b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
