{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT.jar",
          "size": 463616,
          "sha512": "b7b8c5d7c471ba0e5bdc24aa43b41d17562fbe44f62b353e70cf5a1a68ba489591f5b8df5275fe2bb0c96f8697593fbce5b636002befc8d93187ca7fdfd991bc",
          "sha256": "b9ca4f806f18e612628a3d2ae3151efc1099355fd6c4bda589a1309beac63f01",
          "sha1": "97d5423f1484284e8fade4d9c5ae7dc311e8f280",
          "md5": "68c9265523a9ec4f2175e4f90de399a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT.jar",
          "size": 463616,
          "sha512": "b7b8c5d7c471ba0e5bdc24aa43b41d17562fbe44f62b353e70cf5a1a68ba489591f5b8df5275fe2bb0c96f8697593fbce5b636002befc8d93187ca7fdfd991bc",
          "sha256": "b9ca4f806f18e612628a3d2ae3151efc1099355fd6c4bda589a1309beac63f01",
          "sha1": "97d5423f1484284e8fade4d9c5ae7dc311e8f280",
          "md5": "68c9265523a9ec4f2175e4f90de399a3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT-sources.jar",
          "size": 55096,
          "sha512": "e22c5889e1c8bd1c09913ba2500b1d1d0ea01ae519151a1a129c5ad0ae39a3379bfc06ad6e7de43701f7a1e06a1a3b0f6471b5b8e7699922b46f80463b924a6c",
          "sha256": "3ed2d3995c5b3b99c9e18ad1c0b0265170a00cf2c333255ac3e3c52476ff0583",
          "sha1": "7c3338ee48d55d3c2429388dfed46fcb09a97e34",
          "md5": "03bc966d2c953b25395a23e3d8d0d295"
        },
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT-sources.jar",
          "size": 55096,
          "sha512": "e22c5889e1c8bd1c09913ba2500b1d1d0ea01ae519151a1a129c5ad0ae39a3379bfc06ad6e7de43701f7a1e06a1a3b0f6471b5b8e7699922b46f80463b924a6c",
          "sha256": "3ed2d3995c5b3b99c9e18ad1c0b0265170a00cf2c333255ac3e3c52476ff0583",
          "sha1": "7c3338ee48d55d3c2429388dfed46fcb09a97e34",
          "md5": "03bc966d2c953b25395a23e3d8d0d295"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
