{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT.jar",
          "size": 443404,
          "sha512": "f629ac62b2a7a5d28ab5f14b904688b2989222deb43c2213cbef4b68005aec27a75f1bcf527acdc393c19e9c23220dc0da05671f2777b833f104e99151bf9e59",
          "sha256": "fc451965401a99df7cfb882be19c95913d01207fad36a40294b3d6d447f478a3",
          "sha1": "27984384d538a0360b43387898bd0a93e36b6dc2",
          "md5": "13011d7bd30d91dc4b5f33f8b1f1b40d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT.jar",
          "size": 443404,
          "sha512": "f629ac62b2a7a5d28ab5f14b904688b2989222deb43c2213cbef4b68005aec27a75f1bcf527acdc393c19e9c23220dc0da05671f2777b833f104e99151bf9e59",
          "sha256": "fc451965401a99df7cfb882be19c95913d01207fad36a40294b3d6d447f478a3",
          "sha1": "27984384d538a0360b43387898bd0a93e36b6dc2",
          "md5": "13011d7bd30d91dc4b5f33f8b1f1b40d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT-sources.jar",
          "size": 54067,
          "sha512": "ac63143ac512dfae5f98e153d40a9dfef1e19209bfa05feab26b77a81aaffd79094034bf6abe3f449393541b04170c410faadf707aa88a153de4a781bafe7113",
          "sha256": "8535b181c6a3c168e858daad1291c12161c4dcf42752db5f978415becc8479aa",
          "sha1": "d0c9959fba6173cf74e0a38b547b464ac69a0db3",
          "md5": "220476e031936e0614da4d259b69d340"
        },
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT-sources.jar",
          "size": 54067,
          "sha512": "ac63143ac512dfae5f98e153d40a9dfef1e19209bfa05feab26b77a81aaffd79094034bf6abe3f449393541b04170c410faadf707aa88a153de4a781bafe7113",
          "sha256": "8535b181c6a3c168e858daad1291c12161c4dcf42752db5f978415becc8479aa",
          "sha1": "d0c9959fba6173cf74e0a38b547b464ac69a0db3",
          "md5": "220476e031936e0614da4d259b69d340"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
