{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT.jar",
          "size": 442822,
          "sha512": "d3a2be5ebbc69ce3c9481c90161acebfd9e837c3f8866109b68ae3bd0a9e77fbbbf55ffb361b217d91f2b7ce12a6eac7799ad06c8fad46258a77f45d24583a4e",
          "sha256": "0f6a1b781331de17da4ffd77f5471afc7468d5aad59ce3398b3e8d6a6490aa18",
          "sha1": "953f5534b3a74244bb5ec024ca4c7a641bd510a6",
          "md5": "838273e077ff87941bc54863031eb038"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT.jar",
          "size": 442822,
          "sha512": "d3a2be5ebbc69ce3c9481c90161acebfd9e837c3f8866109b68ae3bd0a9e77fbbbf55ffb361b217d91f2b7ce12a6eac7799ad06c8fad46258a77f45d24583a4e",
          "sha256": "0f6a1b781331de17da4ffd77f5471afc7468d5aad59ce3398b3e8d6a6490aa18",
          "sha1": "953f5534b3a74244bb5ec024ca4c7a641bd510a6",
          "md5": "838273e077ff87941bc54863031eb038"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT-sources.jar",
          "size": 54214,
          "sha512": "fff1d8da1e91459800f76e120b507b11d77d6686ce233edbb396d7867df52b5493154649d7a3190a89677eca457a862dfc2d084b31bc2781c80fe11b5a98833b",
          "sha256": "6afbf4933734247f431d97a6404401d94f46d2b103206750da39a77df60afbdb",
          "sha1": "465d2bb598778c0a13f434c835b5085ca30c7186",
          "md5": "d0d0f24c1da5d57a16e9e2e1c8fe64cb"
        },
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT-sources.jar",
          "size": 54214,
          "sha512": "fff1d8da1e91459800f76e120b507b11d77d6686ce233edbb396d7867df52b5493154649d7a3190a89677eca457a862dfc2d084b31bc2781c80fe11b5a98833b",
          "sha256": "6afbf4933734247f431d97a6404401d94f46d2b103206750da39a77df60afbdb",
          "sha1": "465d2bb598778c0a13f434c835b5085ca30c7186",
          "md5": "d0d0f24c1da5d57a16e9e2e1c8fe64cb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
