{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT.jar",
          "size": 463842,
          "sha512": "cc071ad8e16488383149210e33bffd9ca9ecb884c1db0807aa902b023625165f937b3602a042545b3f18b3c246c550a78f68fa201789a01261de2b4a80ed90ae",
          "sha256": "c2b946e872f5051b05fa5772076eab72a9b68f1acb01c394aeb67a450a49c2bf",
          "sha1": "6279ffbd55958763d6c67afdd59ce813918aab60",
          "md5": "470914b3f442b2b2f37bdaed32f0f338"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT.jar",
          "size": 463842,
          "sha512": "cc071ad8e16488383149210e33bffd9ca9ecb884c1db0807aa902b023625165f937b3602a042545b3f18b3c246c550a78f68fa201789a01261de2b4a80ed90ae",
          "sha256": "c2b946e872f5051b05fa5772076eab72a9b68f1acb01c394aeb67a450a49c2bf",
          "sha1": "6279ffbd55958763d6c67afdd59ce813918aab60",
          "md5": "470914b3f442b2b2f37bdaed32f0f338"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT-sources.jar",
          "size": 55211,
          "sha512": "6301608d870ffc1975b193666524fbbc3958d69341e8bb58a6796f26b844afebbb037f5e2ad7c3004b3687259631d2294d8a699bca2134bb5cd856646b0a5c99",
          "sha256": "5b8a684b96a0456ee50094eeeb0835b6c6b1c27931cfe046fcc1180148547d2a",
          "sha1": "83ac40303af23c2cc21506ef684425bc64b7b530",
          "md5": "e8ab9f36ecbc7774feeb0b137e177c8f"
        },
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT-sources.jar",
          "size": 55211,
          "sha512": "6301608d870ffc1975b193666524fbbc3958d69341e8bb58a6796f26b844afebbb037f5e2ad7c3004b3687259631d2294d8a699bca2134bb5cd856646b0a5c99",
          "sha256": "5b8a684b96a0456ee50094eeeb0835b6c6b1c27931cfe046fcc1180148547d2a",
          "sha1": "83ac40303af23c2cc21506ef684425bc64b7b530",
          "md5": "e8ab9f36ecbc7774feeb0b137e177c8f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
