{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT.jar",
          "size": 409369,
          "sha512": "2ad209f4cf19c5a4feb6753cc5d51774660e65a735e7c1fcdde64e09cb5394d7e211511baf8210791546099ac6b3bfefdd9b85bbee3c05b39e529d6bddfa4b16",
          "sha256": "a0d25e00bb75fae824fd3efbfba9fb3a5c9db24365228a47ce1ed521c856ea48",
          "sha1": "9cf3e51c84e4929c3324d3bb1ca1960413442c41",
          "md5": "8ba40f9725ec0bc471106bfeac13477c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT.jar",
          "size": 409369,
          "sha512": "2ad209f4cf19c5a4feb6753cc5d51774660e65a735e7c1fcdde64e09cb5394d7e211511baf8210791546099ac6b3bfefdd9b85bbee3c05b39e529d6bddfa4b16",
          "sha256": "a0d25e00bb75fae824fd3efbfba9fb3a5c9db24365228a47ce1ed521c856ea48",
          "sha1": "9cf3e51c84e4929c3324d3bb1ca1960413442c41",
          "md5": "8ba40f9725ec0bc471106bfeac13477c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT-sources.jar",
          "size": 59129,
          "sha512": "449a7ba2fe7ed9b3eb2032a9750e4295f879ce6726222c36d1705c6efe295c670759a2eabb17f2f4513b8394383cba7cc3cd77d7fa0811b8a0d8e2892805e9f4",
          "sha256": "5535f70d6c1e0d0cf3b6bee21d0314024ce64aa26f4b1a3f7dae4c3e071bf913",
          "sha1": "94f9ed101c9ec6fcfcfe8f1cd6baa5690f75dfa7",
          "md5": "ee40764bcccbefad19ffff3ed40a5ab2"
        },
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT-sources.jar",
          "size": 59129,
          "sha512": "449a7ba2fe7ed9b3eb2032a9750e4295f879ce6726222c36d1705c6efe295c670759a2eabb17f2f4513b8394383cba7cc3cd77d7fa0811b8a0d8e2892805e9f4",
          "sha256": "5535f70d6c1e0d0cf3b6bee21d0314024ce64aa26f4b1a3f7dae4c3e071bf913",
          "sha1": "94f9ed101c9ec6fcfcfe8f1cd6baa5690f75dfa7",
          "md5": "ee40764bcccbefad19ffff3ed40a5ab2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
