{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT.jar",
          "size": 409499,
          "sha512": "c48fc490396d37a906403b862c7d2d1eaae8f57ccfada4393f606053b85e6f07ba6d7c49323bf89c56f136d9a104d30cee6614bef45f6f53aea7991c17ee7785",
          "sha256": "08b65ae33453155ce1a818f159d33236de339ac4a2fd38f8b94e3d6537edae31",
          "sha1": "f94c52bf8c0716c5a8f8fd737dd0ddb196ff83d9",
          "md5": "18fafe41e6bf08b72f5b74f2409f3452"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT.jar",
          "size": 409499,
          "sha512": "c48fc490396d37a906403b862c7d2d1eaae8f57ccfada4393f606053b85e6f07ba6d7c49323bf89c56f136d9a104d30cee6614bef45f6f53aea7991c17ee7785",
          "sha256": "08b65ae33453155ce1a818f159d33236de339ac4a2fd38f8b94e3d6537edae31",
          "sha1": "f94c52bf8c0716c5a8f8fd737dd0ddb196ff83d9",
          "md5": "18fafe41e6bf08b72f5b74f2409f3452"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT-sources.jar",
          "size": 59142,
          "sha512": "0ee0523c341df862bbdf3232952371d7a270a076c0b28aaca12eb5b128f8cdd5d395053fac104857c8dea8120019131e4641fa2167910f689a649acd29fbf248",
          "sha256": "09c26e21d4c49dcb0571bab54d370bc0615c3c1047afacdd293b327ff1c668c0",
          "sha1": "dc01d50fef864f531640ac83febda5f9a9e9ce3f",
          "md5": "0810580ff4e1bdaabec42c166767106a"
        },
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT-sources.jar",
          "size": 59142,
          "sha512": "0ee0523c341df862bbdf3232952371d7a270a076c0b28aaca12eb5b128f8cdd5d395053fac104857c8dea8120019131e4641fa2167910f689a649acd29fbf248",
          "sha256": "09c26e21d4c49dcb0571bab54d370bc0615c3c1047afacdd293b327ff1c668c0",
          "sha1": "dc01d50fef864f531640ac83febda5f9a9e9ce3f",
          "md5": "0810580ff4e1bdaabec42c166767106a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.4.0-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-1.4.0-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
