{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.2.0-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.2.0-SNAPSHOT.jar",
          "size": 409587,
          "sha512": "fbc0ea1614b47a2ddb3892756bee52df102dc79df13187ea9565d690720aa57149cd64fa06b02c48eab4e2eefe6f52f3704bb87dd325ace6dc4be8c81481a931",
          "sha256": "1084a60da376e19c3852925dcfad5e1e8a662bd3921ff805d2e00af46ab31574",
          "sha1": "1b8393886daa501ecb1b9c9830c50917ace4db38",
          "md5": "f0db5bdd296482ba3208496ea7de6b4d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.2.0-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.2.0-SNAPSHOT.jar",
          "size": 409587,
          "sha512": "fbc0ea1614b47a2ddb3892756bee52df102dc79df13187ea9565d690720aa57149cd64fa06b02c48eab4e2eefe6f52f3704bb87dd325ace6dc4be8c81481a931",
          "sha256": "1084a60da376e19c3852925dcfad5e1e8a662bd3921ff805d2e00af46ab31574",
          "sha1": "1b8393886daa501ecb1b9c9830c50917ace4db38",
          "md5": "f0db5bdd296482ba3208496ea7de6b4d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.2.0-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.2.0-SNAPSHOT-sources.jar",
          "size": 50899,
          "sha512": "35195ff32610ce91881c3f7877eb139ae5cef8c268098757fcc4e72430cfe1e9192c86f3eaf5d004ca17c65613fb75f011976ee6ef3d66fbb39d639d5527ad9b",
          "sha256": "35c9292e3b349aafff21c97730c73381b3f8510c64e647af3c539ac9e2e0d23e",
          "sha1": "f230bb47819cd153a033cb199ceb523fd2970b56",
          "md5": "eae04231ad068b4f38063a7f950a3d0b"
        },
        {
          "name": "dokkatoo-plugin-1.2.0-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.2.0-SNAPSHOT-sources.jar",
          "size": 50899,
          "sha512": "35195ff32610ce91881c3f7877eb139ae5cef8c268098757fcc4e72430cfe1e9192c86f3eaf5d004ca17c65613fb75f011976ee6ef3d66fbb39d639d5527ad9b",
          "sha256": "35c9292e3b349aafff21c97730c73381b3f8510c64e647af3c539ac9e2e0d23e",
          "sha1": "f230bb47819cd153a033cb199ceb523fd2970b56",
          "md5": "eae04231ad068b4f38063a7f950a3d0b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.2.0-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-1.2.0-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
