{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.2-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.1.2-SNAPSHOT.jar",
          "size": 391074,
          "sha512": "35d653836e92ef0fbaa8209c3e15495852802a516b20d96f6e2eed2008cc171050624726d0abc5db0ff98b3ba622ae40ec6910c959197662aa518d1604f21646",
          "sha256": "4f8eeca62c224eba07c072adfdedef4ae25d93ad5c6599ce24efda96de69ebc0",
          "sha1": "bc8f4c03d63075a218ac5182390f593d29978719",
          "md5": "bc020e2faabb6f96fb8332ffd1e1391f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.2-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.1.2-SNAPSHOT.jar",
          "size": 391074,
          "sha512": "35d653836e92ef0fbaa8209c3e15495852802a516b20d96f6e2eed2008cc171050624726d0abc5db0ff98b3ba622ae40ec6910c959197662aa518d1604f21646",
          "sha256": "4f8eeca62c224eba07c072adfdedef4ae25d93ad5c6599ce24efda96de69ebc0",
          "sha1": "bc8f4c03d63075a218ac5182390f593d29978719",
          "md5": "bc020e2faabb6f96fb8332ffd1e1391f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.2-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.1.2-SNAPSHOT-sources.jar",
          "size": 49503,
          "sha512": "314d1b45e83ddd62b361a40c586d8b93233d403849fe7457933332e30bc0cd75181f048e704a574a9d9e38e2780e477d43537e82ec7db99735d9a0006a29ecca",
          "sha256": "6eb2fa0230c6d58156bf3d01ab55e6dd0dc9fd69c5ad5797705bc10a525cc42e",
          "sha1": "be5f3e3bda15d145a075b056294f7ca526f7efc0",
          "md5": "25ffea9380c8807a26d79d8f56e5beb4"
        },
        {
          "name": "dokkatoo-plugin-1.1.2-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.1.2-SNAPSHOT-sources.jar",
          "size": 49503,
          "sha512": "314d1b45e83ddd62b361a40c586d8b93233d403849fe7457933332e30bc0cd75181f048e704a574a9d9e38e2780e477d43537e82ec7db99735d9a0006a29ecca",
          "sha256": "6eb2fa0230c6d58156bf3d01ab55e6dd0dc9fd69c5ad5797705bc10a525cc42e",
          "sha1": "be5f3e3bda15d145a075b056294f7ca526f7efc0",
          "md5": "25ffea9380c8807a26d79d8f56e5beb4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.2-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-1.1.2-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
