{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.2-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.1.2-SNAPSHOT.jar",
          "size": 409587,
          "sha512": "c124d69b19d253cfafc5e49d8b104477ca7988b80ea200e620e2d23d35202e4af76e30cff1bd9c9c62eda9b85ced87fb2577543bead69e656da79e0a57aec108",
          "sha256": "4674f345ed21e5e6d1700843ae4001cebfb6d4f373ce87fbc6f0db8792fcf887",
          "sha1": "d6fbd40d27f4891b5edb484df8fccc14bb51e591",
          "md5": "335df9a1e6b450cdbfe49c2a68fd9d84"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.2-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.1.2-SNAPSHOT.jar",
          "size": 409587,
          "sha512": "c124d69b19d253cfafc5e49d8b104477ca7988b80ea200e620e2d23d35202e4af76e30cff1bd9c9c62eda9b85ced87fb2577543bead69e656da79e0a57aec108",
          "sha256": "4674f345ed21e5e6d1700843ae4001cebfb6d4f373ce87fbc6f0db8792fcf887",
          "sha1": "d6fbd40d27f4891b5edb484df8fccc14bb51e591",
          "md5": "335df9a1e6b450cdbfe49c2a68fd9d84"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.2-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.1.2-SNAPSHOT-sources.jar",
          "size": 50898,
          "sha512": "2938c9f7df3a68091890ffc948beac1d000f728dc2755e0cf61042541526e9bd91835fab3fd49ed2b17da6d7ef9361772da3b9329261d6fc9247c15663ae2cc3",
          "sha256": "64b89ea248ad377599eb592db822adfc8c4984f02474036eebd1c8943112e971",
          "sha1": "52271423a9f38d8a6a0f2f22c575b8363d1fd001",
          "md5": "d65ae5df31bc4388c2387572219bd104"
        },
        {
          "name": "dokkatoo-plugin-1.1.2-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.1.2-SNAPSHOT-sources.jar",
          "size": 50898,
          "sha512": "2938c9f7df3a68091890ffc948beac1d000f728dc2755e0cf61042541526e9bd91835fab3fd49ed2b17da6d7ef9361772da3b9329261d6fc9247c15663ae2cc3",
          "sha256": "64b89ea248ad377599eb592db822adfc8c4984f02474036eebd1c8943112e971",
          "sha1": "52271423a9f38d8a6a0f2f22c575b8363d1fd001",
          "md5": "d65ae5df31bc4388c2387572219bd104"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.2-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-1.1.2-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
