{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.2-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.1.2-SNAPSHOT.jar",
          "size": 423206,
          "sha512": "53820843f5697ddc82d12dc8bd4ba59df3ba8853c4aa5ffa0bdd705b3c0a861bbffffc1d08333b75342ca643b890c98da2f916299520592eb72726327d5075c3",
          "sha256": "f776879f49be435cb800b248ee39d802403cec97b226f186f2f0a83f9a145769",
          "sha1": "1fd108642b65fd04afe29400fd4dbc6969f64e53",
          "md5": "f462a63ded203e1bc58b215d740988f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.2-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.1.2-SNAPSHOT.jar",
          "size": 423206,
          "sha512": "53820843f5697ddc82d12dc8bd4ba59df3ba8853c4aa5ffa0bdd705b3c0a861bbffffc1d08333b75342ca643b890c98da2f916299520592eb72726327d5075c3",
          "sha256": "f776879f49be435cb800b248ee39d802403cec97b226f186f2f0a83f9a145769",
          "sha1": "1fd108642b65fd04afe29400fd4dbc6969f64e53",
          "md5": "f462a63ded203e1bc58b215d740988f0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.2-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.1.2-SNAPSHOT-sources.jar",
          "size": 52162,
          "sha512": "dabd0c4acd22a23a15e7a4540d61b3dbdb9051590474f3bb80fb352990879963be3df58022b6502c6a468bf1f600aebd9f112d23455854fa3af068ef9fea5a8d",
          "sha256": "b76214f174997fab3c266bcf04558ab523fa6219cd1cd55b978c7cdcb627e0c1",
          "sha1": "22e90764992d775e88bb4328d1f8dd9fb1dbd33d",
          "md5": "dbcc51c05dd02995ce9887eaae25f94d"
        },
        {
          "name": "dokkatoo-plugin-1.1.2-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.1.2-SNAPSHOT-sources.jar",
          "size": 52162,
          "sha512": "dabd0c4acd22a23a15e7a4540d61b3dbdb9051590474f3bb80fb352990879963be3df58022b6502c6a468bf1f600aebd9f112d23455854fa3af068ef9fea5a8d",
          "sha256": "b76214f174997fab3c266bcf04558ab523fa6219cd1cd55b978c7cdcb627e0c1",
          "sha1": "22e90764992d775e88bb4328d1f8dd9fb1dbd33d",
          "md5": "dbcc51c05dd02995ce9887eaae25f94d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.2-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-1.1.2-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
