{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.6.0-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.6.0-SNAPSHOT.jar",
          "size": 425653,
          "sha512": "5a305d0e733480e936c2e53825c1c88e1de19feaa9d6a5e19b9836c2376b2841042a19571a3f527eb6f08092b282cbcb845426c73b90cd11d8c53fd1e9cf4734",
          "sha256": "e2e6e3ca188d3cb3775ee8fc125ea7ff26f404d2085ed90bd49e11875107f37a",
          "sha1": "6b021f75bba490dd1fd10f8f320052a4f83f865e",
          "md5": "dd99d8f7e2a65d82af2c99ec77daae24"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.6.0-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.6.0-SNAPSHOT.jar",
          "size": 425653,
          "sha512": "5a305d0e733480e936c2e53825c1c88e1de19feaa9d6a5e19b9836c2376b2841042a19571a3f527eb6f08092b282cbcb845426c73b90cd11d8c53fd1e9cf4734",
          "sha256": "e2e6e3ca188d3cb3775ee8fc125ea7ff26f404d2085ed90bd49e11875107f37a",
          "sha1": "6b021f75bba490dd1fd10f8f320052a4f83f865e",
          "md5": "dd99d8f7e2a65d82af2c99ec77daae24"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.6.0-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.6.0-SNAPSHOT-sources.jar",
          "size": 61614,
          "sha512": "91965ed4f2bab58cf241f73e3080a6bae2f33c09227dccf1cf81f0faa2bc7111b004a1b1b1aa5b8d5eb682de6f1a49d336dda452b34c83825463afcba9b1bb33",
          "sha256": "ec5d1c3144722069800d8f971ab21c1744a43d4201f546fe66b337314f701045",
          "sha1": "253c64e40630be7b242a1ef0217f180bae2f07ca",
          "md5": "7e0ddc83493d6d680b340625fc9c516e"
        },
        {
          "name": "dokkatoo-plugin-1.6.0-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.6.0-SNAPSHOT-sources.jar",
          "size": 61614,
          "sha512": "91965ed4f2bab58cf241f73e3080a6bae2f33c09227dccf1cf81f0faa2bc7111b004a1b1b1aa5b8d5eb682de6f1a49d336dda452b34c83825463afcba9b1bb33",
          "sha256": "ec5d1c3144722069800d8f971ab21c1744a43d4201f546fe66b337314f701045",
          "sha1": "253c64e40630be7b242a1ef0217f180bae2f07ca",
          "md5": "7e0ddc83493d6d680b340625fc9c516e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.6.0-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-1.6.0-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
