{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.5.0-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.5.0-SNAPSHOT.jar",
          "size": 425655,
          "sha512": "63efb02ecd9a0baa4a31c1e529100822be5d75d655e03fb6c68ae3e038c84b086039e9aad6547eefb48d4ad4dff7a1daa77b323a1fce330c0596fedccd98b556",
          "sha256": "8af57d7670fc6ef6d0e1e4a92291e3c5635bd59ed10c6d3a8f26a21ad3eedaf8",
          "sha1": "b8533097f9cc4893be58aad8b6313d10a8332564",
          "md5": "7e2f7f7c893a51e17af41525b254c115"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.5.0-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.5.0-SNAPSHOT.jar",
          "size": 425655,
          "sha512": "63efb02ecd9a0baa4a31c1e529100822be5d75d655e03fb6c68ae3e038c84b086039e9aad6547eefb48d4ad4dff7a1daa77b323a1fce330c0596fedccd98b556",
          "sha256": "8af57d7670fc6ef6d0e1e4a92291e3c5635bd59ed10c6d3a8f26a21ad3eedaf8",
          "sha1": "b8533097f9cc4893be58aad8b6313d10a8332564",
          "md5": "7e2f7f7c893a51e17af41525b254c115"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.5.0-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.5.0-SNAPSHOT-sources.jar",
          "size": 61615,
          "sha512": "77e27b69ba76c0e5b825348b1876957d4573d5ede89d39b87fd3a2b30570fdf006ab261b3e76f571ce0ce0a9b7e13cdae2d10cf0b366ffd536b1ad352d3b9429",
          "sha256": "28226be70e66bd35168a618c48d67dbafa9e84c5d4b7343d699a0a0dbe22f4a9",
          "sha1": "13bd3013aa388ff14698ab980c430ec2281e864a",
          "md5": "d73d6386e62a45ac7ae868877fe2f936"
        },
        {
          "name": "dokkatoo-plugin-1.5.0-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.5.0-SNAPSHOT-sources.jar",
          "size": 61615,
          "sha512": "77e27b69ba76c0e5b825348b1876957d4573d5ede89d39b87fd3a2b30570fdf006ab261b3e76f571ce0ce0a9b7e13cdae2d10cf0b366ffd536b1ad352d3b9429",
          "sha256": "28226be70e66bd35168a618c48d67dbafa9e84c5d4b7343d699a0a0dbe22f4a9",
          "sha1": "13bd3013aa388ff14698ab980c430ec2281e864a",
          "md5": "d73d6386e62a45ac7ae868877fe2f936"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.5.0-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-1.5.0-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
