{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.5.0-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.5.0-SNAPSHOT.jar",
          "size": 425658,
          "sha512": "7d62c75bb629ed4797411c15d9849515d0bc2ff844d0ece0fc6773e8bcf50b028ffa6bd398e5adc6e3f920b449fe6b1e4331a186174870fa60d796dc6e725de6",
          "sha256": "c4a109dd44e8415b7e31a1957912d7defebe22b546e4d40fbaf4ae9052fcd499",
          "sha1": "eeb58c217b44261b9780c16b53ec5dde16b0a848",
          "md5": "b5edb77f185c296cf9b6ab4775f7f224"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.5.0-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.5.0-SNAPSHOT.jar",
          "size": 425658,
          "sha512": "7d62c75bb629ed4797411c15d9849515d0bc2ff844d0ece0fc6773e8bcf50b028ffa6bd398e5adc6e3f920b449fe6b1e4331a186174870fa60d796dc6e725de6",
          "sha256": "c4a109dd44e8415b7e31a1957912d7defebe22b546e4d40fbaf4ae9052fcd499",
          "sha1": "eeb58c217b44261b9780c16b53ec5dde16b0a848",
          "md5": "b5edb77f185c296cf9b6ab4775f7f224"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.5.0-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.5.0-SNAPSHOT-sources.jar",
          "size": 61615,
          "sha512": "8180c21c140bf95b4452ac338ca8835f6756d7e91eca4f8565a7bcf2d0429d9f580bb41729ad420d7c9b2ec6b0f90823bdca8ba40cfb81a0bd7fde2cb60e4f16",
          "sha256": "8864e51be637a3e109b929dfa4e997cdcbfea75434f16cfd47ec2e4f954b5184",
          "sha1": "26b0b969ca0032ed40d7730e1379498bb9e0379c",
          "md5": "d11ae7f7be5d0feedfc4cf33cbba28f3"
        },
        {
          "name": "dokkatoo-plugin-1.5.0-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.5.0-SNAPSHOT-sources.jar",
          "size": 61615,
          "sha512": "8180c21c140bf95b4452ac338ca8835f6756d7e91eca4f8565a7bcf2d0429d9f580bb41729ad420d7c9b2ec6b0f90823bdca8ba40cfb81a0bd7fde2cb60e4f16",
          "sha256": "8864e51be637a3e109b929dfa4e997cdcbfea75434f16cfd47ec2e4f954b5184",
          "sha1": "26b0b969ca0032ed40d7730e1379498bb9e0379c",
          "md5": "d11ae7f7be5d0feedfc4cf33cbba28f3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.5.0-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-1.5.0-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
