{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.5.0-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.5.0-SNAPSHOT.jar",
          "size": 425659,
          "sha512": "8ab7be2bafa6cb49c2d03d09904237db4ff6c4bd90a7f2f5e431ec76842c4385501c471d531368f629341154fe1cb9e3ae4f159c549a3fd465ac7b60b5a0a9f8",
          "sha256": "1fbe6609a0ac532c3c9cc0776cbbcca85bdc013d7c553fb62fa8e15314029eea",
          "sha1": "2b970f272d75fb62b29771ff8f6bb8b1788e8367",
          "md5": "4f9bc4d0325b63253e6a24997ab7ef7c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.5.0-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-1.5.0-SNAPSHOT.jar",
          "size": 425659,
          "sha512": "8ab7be2bafa6cb49c2d03d09904237db4ff6c4bd90a7f2f5e431ec76842c4385501c471d531368f629341154fe1cb9e3ae4f159c549a3fd465ac7b60b5a0a9f8",
          "sha256": "1fbe6609a0ac532c3c9cc0776cbbcca85bdc013d7c553fb62fa8e15314029eea",
          "sha1": "2b970f272d75fb62b29771ff8f6bb8b1788e8367",
          "md5": "4f9bc4d0325b63253e6a24997ab7ef7c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.5.0-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.5.0-SNAPSHOT-sources.jar",
          "size": 61615,
          "sha512": "8180c21c140bf95b4452ac338ca8835f6756d7e91eca4f8565a7bcf2d0429d9f580bb41729ad420d7c9b2ec6b0f90823bdca8ba40cfb81a0bd7fde2cb60e4f16",
          "sha256": "8864e51be637a3e109b929dfa4e997cdcbfea75434f16cfd47ec2e4f954b5184",
          "sha1": "26b0b969ca0032ed40d7730e1379498bb9e0379c",
          "md5": "d11ae7f7be5d0feedfc4cf33cbba28f3"
        },
        {
          "name": "dokkatoo-plugin-1.5.0-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-1.5.0-SNAPSHOT-sources.jar",
          "size": 61615,
          "sha512": "8180c21c140bf95b4452ac338ca8835f6756d7e91eca4f8565a7bcf2d0429d9f580bb41729ad420d7c9b2ec6b0f90823bdca8ba40cfb81a0bd7fde2cb60e4f16",
          "sha256": "8864e51be637a3e109b929dfa4e997cdcbfea75434f16cfd47ec2e4f954b5184",
          "sha1": "26b0b969ca0032ed40d7730e1379498bb9e0379c",
          "md5": "d11ae7f7be5d0feedfc4cf33cbba28f3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.5.0-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-1.5.0-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
