{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.0.jar",
          "url": "dokkatoo-plugin-1.1.0.jar",
          "size": 385758,
          "sha512": "f9fc717c46144a6fc029e9469c6f0e19f851c26b278db519ac5b9080b7a3459514172a86de6c0a1621c38a91012d254d739fbe17c0d8c10555abfeef61373dbd",
          "sha256": "570915293a8be771afdae10723d2de63e39d0a65b2cf16485870c1bb2f409a0c",
          "sha1": "98e133a61d854a0316cd37e2c52ba72fe8c1f4a9",
          "md5": "46273f99884c4211da4571fd6b5250d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.0.jar",
          "url": "dokkatoo-plugin-1.1.0.jar",
          "size": 385758,
          "sha512": "f9fc717c46144a6fc029e9469c6f0e19f851c26b278db519ac5b9080b7a3459514172a86de6c0a1621c38a91012d254d739fbe17c0d8c10555abfeef61373dbd",
          "sha256": "570915293a8be771afdae10723d2de63e39d0a65b2cf16485870c1bb2f409a0c",
          "sha1": "98e133a61d854a0316cd37e2c52ba72fe8c1f4a9",
          "md5": "46273f99884c4211da4571fd6b5250d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.0-sources.jar",
          "url": "dokkatoo-plugin-1.1.0-sources.jar",
          "size": 49011,
          "sha512": "8a18b1653a506d1ffb2f6c89f708f3b820f7cf8d3ca7f53baaa10c8c25c00b7e4f1379b7a19c1afe3fd02e6b760866fe2771dba5386689c5354a631380663e88",
          "sha256": "ef4bdac5310cc13f85572b22dfbae4d3dde0c3296b0a613f14ddd1c6513c9045",
          "sha1": "9c2e3fb5e7bfd4439dc32d12a77b65327c3c580b",
          "md5": "72727ae40a1a4bba581dd1d78582a8dd"
        },
        {
          "name": "dokkatoo-plugin-1.1.0-sources.jar",
          "url": "dokkatoo-plugin-1.1.0-sources.jar",
          "size": 49011,
          "sha512": "8a18b1653a506d1ffb2f6c89f708f3b820f7cf8d3ca7f53baaa10c8c25c00b7e4f1379b7a19c1afe3fd02e6b760866fe2771dba5386689c5354a631380663e88",
          "sha256": "ef4bdac5310cc13f85572b22dfbae4d3dde0c3296b0a613f14ddd1c6513c9045",
          "sha1": "9c2e3fb5e7bfd4439dc32d12a77b65327c3c580b",
          "md5": "72727ae40a1a4bba581dd1d78582a8dd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.0-javadoc.jar",
          "url": "dokkatoo-plugin-1.1.0-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
