{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.4.jar",
          "url": "dokkatoo-plugin-0.0.4.jar",
          "size": 322464,
          "sha512": "4393a924cae756008e3c93cc373c8c187cbffc0b7c62e7ea9a0ace0f587fedbfbfe6e7a0aeacc886f26fe9b3952083f7347919aef73ed49cf5832ef9fa846b44",
          "sha256": "67fd308e088283742347c5b8eac1017590771e762e460423dcd5b63514746847",
          "sha1": "f34dcde9c4c1c07d1aea03d6019a9e4524991be7",
          "md5": "04683245e4e8b4074c0be68006adc221"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.4.jar",
          "url": "dokkatoo-plugin-0.0.4.jar",
          "size": 322464,
          "sha512": "4393a924cae756008e3c93cc373c8c187cbffc0b7c62e7ea9a0ace0f587fedbfbfe6e7a0aeacc886f26fe9b3952083f7347919aef73ed49cf5832ef9fa846b44",
          "sha256": "67fd308e088283742347c5b8eac1017590771e762e460423dcd5b63514746847",
          "sha1": "f34dcde9c4c1c07d1aea03d6019a9e4524991be7",
          "md5": "04683245e4e8b4074c0be68006adc221"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.4-sources.jar",
          "url": "dokkatoo-plugin-0.0.4-sources.jar",
          "size": 38626,
          "sha512": "b46e698ef2dec81720949db41e86286e805460be6625ac0727abd49fe2f4f5450ab89cecd1acbce51020b4ac11621b60aebb99fb94da1d1f4e08280afc8cba4e",
          "sha256": "6719cf0ffdd2da0c74b49712c510c4ea2076f4ffe7b5fcbf96f6919951c9a59b",
          "sha1": "d7db5c0b5a3965ec9e27c37c2c0776eeed75e83e",
          "md5": "878e5bdc4270033aa375622686e9c174"
        },
        {
          "name": "dokkatoo-plugin-0.0.4-sources.jar",
          "url": "dokkatoo-plugin-0.0.4-sources.jar",
          "size": 38626,
          "sha512": "b46e698ef2dec81720949db41e86286e805460be6625ac0727abd49fe2f4f5450ab89cecd1acbce51020b4ac11621b60aebb99fb94da1d1f4e08280afc8cba4e",
          "sha256": "6719cf0ffdd2da0c74b49712c510c4ea2076f4ffe7b5fcbf96f6919951c9a59b",
          "sha1": "d7db5c0b5a3965ec9e27c37c2c0776eeed75e83e",
          "md5": "878e5bdc4270033aa375622686e9c174"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.4-javadoc.jar",
          "url": "dokkatoo-plugin-0.0.4-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
