{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.6.0.jar",
          "url": "dokkatoo-plugin-1.6.0.jar",
          "size": 426339,
          "sha512": "780d53359fcfbfd772c181e9fa887bfc4e7593307883a55a09106bd7df933076dc3e6ec2ea6b7777418455ad1b1e9f052f4d4be7b622db1b115cb86aee92cdc7",
          "sha256": "a4800c953c4c3e8ffcf0e4c904ce20905c56abebf6f0d0a2d56041ddc3fb6cf2",
          "sha1": "3ad825629a9b9cc63753bfe143fabf3d224af43e",
          "md5": "a177f1fa4371c744e73cb93f12dd7823"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.6.0.jar",
          "url": "dokkatoo-plugin-1.6.0.jar",
          "size": 426339,
          "sha512": "780d53359fcfbfd772c181e9fa887bfc4e7593307883a55a09106bd7df933076dc3e6ec2ea6b7777418455ad1b1e9f052f4d4be7b622db1b115cb86aee92cdc7",
          "sha256": "a4800c953c4c3e8ffcf0e4c904ce20905c56abebf6f0d0a2d56041ddc3fb6cf2",
          "sha1": "3ad825629a9b9cc63753bfe143fabf3d224af43e",
          "md5": "a177f1fa4371c744e73cb93f12dd7823"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.6.0-sources.jar",
          "url": "dokkatoo-plugin-1.6.0-sources.jar",
          "size": 61774,
          "sha512": "4e779e21accd894ec1e990292b88cab0b9d130c08fc5b629747423eea79da0048e955fc9344a5f323e38d985cfceb3cd52213d02235f1bae52878f0fb1d68716",
          "sha256": "5bc0f2e0243fd1fee9d5d91ddcf370bfe1b77b2be40850d71c10350f54974c9f",
          "sha1": "5ae35b5c601f49993074b547d831b333ba95a833",
          "md5": "3888c17f458d36f1c38c4dd787f47b76"
        },
        {
          "name": "dokkatoo-plugin-1.6.0-sources.jar",
          "url": "dokkatoo-plugin-1.6.0-sources.jar",
          "size": 61774,
          "sha512": "4e779e21accd894ec1e990292b88cab0b9d130c08fc5b629747423eea79da0048e955fc9344a5f323e38d985cfceb3cd52213d02235f1bae52878f0fb1d68716",
          "sha256": "5bc0f2e0243fd1fee9d5d91ddcf370bfe1b77b2be40850d71c10350f54974c9f",
          "sha1": "5ae35b5c601f49993074b547d831b333ba95a833",
          "md5": "3888c17f458d36f1c38c4dd787f47b76"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.6.0-javadoc.jar",
          "url": "dokkatoo-plugin-1.6.0-javadoc.jar",
          "size": 463,
          "sha512": "07b5da88e980ad5b73e92ed6f6fde23b23d1731dd5a653b210a69d1915aef7b5efa29b1687e5d16287f07fdd3acf5b21d5c7869e4549e4086841bc6c7bcff7d9",
          "sha256": "b460f76c52c4188db19df4e7ee0991dfcedf52774103d79934b85621b1c1ddbb",
          "sha1": "af56a6c9cecd00400b75951f371b04dbf38eb9b1",
          "md5": "6d34be94539a56344fc10abb4b87769e"
        }
      ]
    }
  ]
}
