{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.1.jar",
          "url": "dokkatoo-plugin-1.1.1.jar",
          "size": 391063,
          "sha512": "6abce682dcc4b987c3f0809c3f777845f492c0e3041e8745f61988fe061c792d11267b765f66ce43fce253df4f7598080601fbaa9502f2086c1672d8a372e6f0",
          "sha256": "3d447468e6879ded44399ea8c6a63b044af275c3d048604665a3cc4c3ac9b58e",
          "sha1": "f7a928155f4d82afa8d69435b1ee33ec4305f897",
          "md5": "7e4732c4ba3f8baa377959c5187be433"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.1.jar",
          "url": "dokkatoo-plugin-1.1.1.jar",
          "size": 391063,
          "sha512": "6abce682dcc4b987c3f0809c3f777845f492c0e3041e8745f61988fe061c792d11267b765f66ce43fce253df4f7598080601fbaa9502f2086c1672d8a372e6f0",
          "sha256": "3d447468e6879ded44399ea8c6a63b044af275c3d048604665a3cc4c3ac9b58e",
          "sha1": "f7a928155f4d82afa8d69435b1ee33ec4305f897",
          "md5": "7e4732c4ba3f8baa377959c5187be433"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.1-sources.jar",
          "url": "dokkatoo-plugin-1.1.1-sources.jar",
          "size": 49494,
          "sha512": "3dc2101d68f06db3f2c06f76f84e08f9c02fa5a091003067a4287379626940b5dbad48ad55aca6e90a5ba45db4661c0d35ff7dbe6a42367925dee0950e0a5cea",
          "sha256": "2934bb7d2b738cd04c7692f1221583cf93bd3a44e50bf5a926a83d1718395bd8",
          "sha1": "8dcb8480fe94de559bfb1afa748f3f39e569eee8",
          "md5": "60d25fbcc958ba0badd98060762f1a9a"
        },
        {
          "name": "dokkatoo-plugin-1.1.1-sources.jar",
          "url": "dokkatoo-plugin-1.1.1-sources.jar",
          "size": 49494,
          "sha512": "3dc2101d68f06db3f2c06f76f84e08f9c02fa5a091003067a4287379626940b5dbad48ad55aca6e90a5ba45db4661c0d35ff7dbe6a42367925dee0950e0a5cea",
          "sha256": "2934bb7d2b738cd04c7692f1221583cf93bd3a44e50bf5a926a83d1718395bd8",
          "sha1": "8dcb8480fe94de559bfb1afa748f3f39e569eee8",
          "md5": "60d25fbcc958ba0badd98060762f1a9a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-1.1.1-javadoc.jar",
          "url": "dokkatoo-plugin-1.1.1-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
