{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-base-plugin",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-base-plugin-0.0.1-SNAPSHOT.jar",
          "url": "dokkatoo-base-plugin-0.0.1-SNAPSHOT.jar",
          "size": 280991,
          "sha512": "5904c17a481222ab8586a18b04120021ea7d6c96226dda2c2d1bcd916e9e5f34cd1669cc6bde6c3d788e840fdb07d537744079c5d32d6a064f2c29755cd3662b",
          "sha256": "90e9469b8dd65316b95c97081297ce21d542a463a0971dc26fa7985ee58bfdad",
          "sha1": "6dc98ec7f720132d62d167162602be69df7c9785",
          "md5": "2bbf1494a0b8f8108adca98087e51d13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "dokkatoo-base-plugin-0.0.1-SNAPSHOT.jar",
          "url": "dokkatoo-base-plugin-0.0.1-SNAPSHOT.jar",
          "size": 280991,
          "sha512": "5904c17a481222ab8586a18b04120021ea7d6c96226dda2c2d1bcd916e9e5f34cd1669cc6bde6c3d788e840fdb07d537744079c5d32d6a064f2c29755cd3662b",
          "sha256": "90e9469b8dd65316b95c97081297ce21d542a463a0971dc26fa7985ee58bfdad",
          "sha1": "6dc98ec7f720132d62d167162602be69df7c9785",
          "md5": "2bbf1494a0b8f8108adca98087e51d13"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.adamko.dokkatoo",
          "module": "dokkatoo-base-plugin",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "dokkatoo-base-plugin-0.0.1-SNAPSHOT-test-fixtures.jar",
          "url": "dokkatoo-base-plugin-0.0.1-SNAPSHOT-test-fixtures.jar",
          "size": 21291,
          "sha512": "7a26110a1474eea8c36c9c7a9d30d7a5a663b7fde42d6a44f3520f10ae7612a2c169d473a1791e9d276bf33bcd7f2928d16b56680e3311d4a344a6a24b709f44",
          "sha256": "50148cef4db7758c07b013ecb342d920d6b50bd20281c5eb9abe220aae18805a",
          "sha1": "a2e912c5bb182938f06822856e76682b0871e79f",
          "md5": "a5cee66d34d2455828fd0853f21dc827"
        }
      ],
      "capabilities": [
        {
          "group": "dev.adamko.dokkatoo",
          "name": "dokkatoo-base-plugin-test-fixtures",
          "version": "0.0.1-SNAPSHOT"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "dev.adamko.dokkatoo",
          "module": "dokkatoo-base-plugin",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "dokkatoo-base-plugin-0.0.1-SNAPSHOT-test-fixtures.jar",
          "url": "dokkatoo-base-plugin-0.0.1-SNAPSHOT-test-fixtures.jar",
          "size": 21291,
          "sha512": "7a26110a1474eea8c36c9c7a9d30d7a5a663b7fde42d6a44f3520f10ae7612a2c169d473a1791e9d276bf33bcd7f2928d16b56680e3311d4a344a6a24b709f44",
          "sha256": "50148cef4db7758c07b013ecb342d920d6b50bd20281c5eb9abe220aae18805a",
          "sha1": "a2e912c5bb182938f06822856e76682b0871e79f",
          "md5": "a5cee66d34d2455828fd0853f21dc827"
        }
      ],
      "capabilities": [
        {
          "group": "dev.adamko.dokkatoo",
          "name": "dokkatoo-base-plugin-test-fixtures",
          "version": "0.0.1-SNAPSHOT"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-base-plugin-0.0.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-base-plugin-0.0.1-SNAPSHOT-sources.jar",
          "size": 36245,
          "sha512": "d183ac8d5cb9e100d370d8cf6bac9dbb147c934ccb0340201b95a613fb8d0a54f8087fe95549370b3f1ccc8da19900766ea83d282c4d0df5e140e2cad4cb5c1b",
          "sha256": "8d402daf3c8101d9e8a3b222a614c8ca288eccf6c11b000c05f595ff9c8ee94c",
          "sha1": "0c982dc5263ced2525bc5926d9832a0d434ad7fa",
          "md5": "c6921e1741e3f2ff8523ca5c3d3f17f2"
        },
        {
          "name": "dokkatoo-base-plugin-0.0.1-SNAPSHOT-sources.jar",
          "url": "dokkatoo-base-plugin-0.0.1-SNAPSHOT-sources.jar",
          "size": 36245,
          "sha512": "d183ac8d5cb9e100d370d8cf6bac9dbb147c934ccb0340201b95a613fb8d0a54f8087fe95549370b3f1ccc8da19900766ea83d282c4d0df5e140e2cad4cb5c1b",
          "sha256": "8d402daf3c8101d9e8a3b222a614c8ca288eccf6c11b000c05f595ff9c8ee94c",
          "sha1": "0c982dc5263ced2525bc5926d9832a0d434ad7fa",
          "md5": "c6921e1741e3f2ff8523ca5c3d3f17f2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-base-plugin-0.0.1-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-base-plugin-0.0.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
