name: Clear all GitHub Actions caches

on:
  workflow_dispatch:

jobs:
  my-job:
    name: Delete all caches
    runs-on: ubuntu-latest

    steps:
      - name: Clear caches
        uses: easimon/wipe-cache@v2
