name: Tests


on:
  workflow_dispatch:
  workflow_call:


concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true


permissions:
  contents: read
  checks: write # required by mikepenz/action-junit-report


jobs:

  gradle-check:
    strategy:
      matrix:
        include:
          - os: macos-latest
            task: "check --continue"
          - os: ubuntu-latest
            task: "check --continue"
          - os: windows-latest
            # don't run integration/functional tests on Windows because Gradle OOMs https://github.com/adamko-dev/dokkatoo/issues/10
            task: >-
              check
              --continue
              -x :modules:dokkatoo-plugin-integration-tests:check
              -x :modules:dokkatoo-plugin:testFunctional
              --no-parallel
              --no-configuration-cache
              --no-daemon
              --max-workers=1
              -Dorg.gradle.workers.max=1
      fail-fast: false
    uses: ./.github/workflows/run_gradle_task.yml
    with:
      runs-on: ${{ matrix.os }}
      gradle-task: >-
        ${{ matrix.task }} --stacktrace
