{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "0.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.4-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-0.0.4-SNAPSHOT.jar",
          "size": 323546,
          "sha512": "7f356a236815a1d8f3888fae7926565538f162d8f7f4e39f56ea0d72394a8beb46a92341e43b1c62a36fed0daf50d5fef8dabcfa6e596583ee65664e45654778",
          "sha256": "05d1bfc0caf3bc84962ecaa1c07ffeb1a4b219b728142ac57c1c7a083c9fdae6",
          "sha1": "e8234f74ebd6093104b584e6bbf4b8c45a592d00",
          "md5": "2398f461c87c3c0aee028ecbdd7d9bb3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.4-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-0.0.4-SNAPSHOT.jar",
          "size": 323546,
          "sha512": "7f356a236815a1d8f3888fae7926565538f162d8f7f4e39f56ea0d72394a8beb46a92341e43b1c62a36fed0daf50d5fef8dabcfa6e596583ee65664e45654778",
          "sha256": "05d1bfc0caf3bc84962ecaa1c07ffeb1a4b219b728142ac57c1c7a083c9fdae6",
          "sha1": "e8234f74ebd6093104b584e6bbf4b8c45a592d00",
          "md5": "2398f461c87c3c0aee028ecbdd7d9bb3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.4-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.4-SNAPSHOT-sources.jar",
          "size": 39175,
          "sha512": "75192e9aedf217a5f85f0e787da9764b0f1a0297b1eac5e840bd4546755bd4fe5dd4fa7555fd4d5b5ecdc7a1452f894d3c7ae5f853b599315933582b8f6297ab",
          "sha256": "559a1e1f7bab95ef932dcd58737327acc0d3d21891e07ee8e01e3d0adad67710",
          "sha1": "8e20e7162f87eef8e61b373e9c3006360a59907f",
          "md5": "de6c0d177747d507ecd55f7c72a5e7c8"
        },
        {
          "name": "dokkatoo-plugin-0.0.4-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.4-SNAPSHOT-sources.jar",
          "size": 39175,
          "sha512": "75192e9aedf217a5f85f0e787da9764b0f1a0297b1eac5e840bd4546755bd4fe5dd4fa7555fd4d5b5ecdc7a1452f894d3c7ae5f853b599315933582b8f6297ab",
          "sha256": "559a1e1f7bab95ef932dcd58737327acc0d3d21891e07ee8e01e3d0adad67710",
          "sha1": "8e20e7162f87eef8e61b373e9c3006360a59907f",
          "md5": "de6c0d177747d507ecd55f7c72a5e7c8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.4-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-0.0.4-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
