{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "0.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.4-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-0.0.4-SNAPSHOT.jar",
          "size": 322811,
          "sha512": "7e322261796dedfbc7c94bfcb2a5b5fef1b792bacd6e3fc1a752fc852caf5ea45b9f7df9d02e1c08c83364e37f15ea7574d412409b221073bbe77e9adc373278",
          "sha256": "147a3479c3dcef6dbf8da200644d86950ab01ca744dd543cd226427a058e76a4",
          "sha1": "5ce9ab51f7357a908ead609fa24cad3b10e9a241",
          "md5": "d360aac4e7e108aa96179241452dd960"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.4.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json"
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.4-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-0.0.4-SNAPSHOT.jar",
          "size": 322811,
          "sha512": "7e322261796dedfbc7c94bfcb2a5b5fef1b792bacd6e3fc1a752fc852caf5ea45b9f7df9d02e1c08c83364e37f15ea7574d412409b221073bbe77e9adc373278",
          "sha256": "147a3479c3dcef6dbf8da200644d86950ab01ca744dd543cd226427a058e76a4",
          "sha1": "5ce9ab51f7357a908ead609fa24cad3b10e9a241",
          "md5": "d360aac4e7e108aa96179241452dd960"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.4-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.4-SNAPSHOT-sources.jar",
          "size": 38634,
          "sha512": "1003be46192f089c7598dd0f9db04017f8f848e4efd6ed5fd6ff494585b9e4a415d520b7a525569d5c3abb0c5e3106e4886872773278a48b27beda7e1496203c",
          "sha256": "adb1e5c4d449c21e9611c92b02a27b6a7fa81ae3cdda0a322a1dd1a677d25426",
          "sha1": "97f1270a2e502d8a0f57158cb24677462eb14cfc",
          "md5": "7d4b6692c6a3b336e2fa60498e66077c"
        },
        {
          "name": "dokkatoo-plugin-0.0.4-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.4-SNAPSHOT-sources.jar",
          "size": 38634,
          "sha512": "1003be46192f089c7598dd0f9db04017f8f848e4efd6ed5fd6ff494585b9e4a415d520b7a525569d5c3abb0c5e3106e4886872773278a48b27beda7e1496203c",
          "sha256": "adb1e5c4d449c21e9611c92b02a27b6a7fa81ae3cdda0a322a1dd1a677d25426",
          "sha1": "97f1270a2e502d8a0f57158cb24677462eb14cfc",
          "md5": "7d4b6692c6a3b336e2fa60498e66077c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.4-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-0.0.4-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
