{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.dokkatoo",
    "module": "dokkatoo-plugin",
    "version": "0.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.4-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-0.0.4-SNAPSHOT.jar",
          "size": 324345,
          "sha512": "7a063ad9c6edeba34fe63966307219ea065a63eb0176dc8f704b91e70fe8639352b3b8eab2451bdf39b2e5558dd6bb0786246ea4ccb1b9b27d6e90d15edd908c",
          "sha256": "e8430e2b2afcd93282f9a952c4b5ec0dd6b9b8b34d9c316f6fe0f3eb83ee61af",
          "sha1": "4f8d106a0451121d25f288666b45502c63d7dbe7",
          "md5": "77a8ffdc89be1e0485086fb50d4370cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.4-SNAPSHOT.jar",
          "url": "dokkatoo-plugin-0.0.4-SNAPSHOT.jar",
          "size": 324345,
          "sha512": "7a063ad9c6edeba34fe63966307219ea065a63eb0176dc8f704b91e70fe8639352b3b8eab2451bdf39b2e5558dd6bb0786246ea4ccb1b9b27d6e90d15edd908c",
          "sha256": "e8430e2b2afcd93282f9a952c4b5ec0dd6b9b8b34d9c316f6fe0f3eb83ee61af",
          "sha1": "4f8d106a0451121d25f288666b45502c63d7dbe7",
          "md5": "77a8ffdc89be1e0485086fb50d4370cc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.4-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.4-SNAPSHOT-sources.jar",
          "size": 39925,
          "sha512": "67847cf634edd1e542814df63b4740ef6e1a95af61cb1d010b044fb3dd6ea0a1f2658bef8217540b30cb2c01c9eae283921aeddbd83ec5114fde91d6461f8bd9",
          "sha256": "ff313e3635024c4ecf279618363cc5841df6b64fd4ca5b67d679009029e75aaa",
          "sha1": "53be80c45cf755bd0f30bfab8307f57375675cd8",
          "md5": "763cec515c4d9320715119911eb7b8fd"
        },
        {
          "name": "dokkatoo-plugin-0.0.4-SNAPSHOT-sources.jar",
          "url": "dokkatoo-plugin-0.0.4-SNAPSHOT-sources.jar",
          "size": 39925,
          "sha512": "67847cf634edd1e542814df63b4740ef6e1a95af61cb1d010b044fb3dd6ea0a1f2658bef8217540b30cb2c01c9eae283921aeddbd83ec5114fde91d6461f8bd9",
          "sha256": "ff313e3635024c4ecf279618363cc5841df6b64fd4ca5b67d679009029e75aaa",
          "sha1": "53be80c45cf755bd0f30bfab8307f57375675cd8",
          "md5": "763cec515c4d9320715119911eb7b8fd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokkatoo-plugin-0.0.4-SNAPSHOT-javadoc.jar",
          "url": "dokkatoo-plugin-0.0.4-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
